page crash on trend graph on selecting 3 month/1 year data
chef/automate pull request #4489
Opened 2020-12-16 17:24 UTC by shaik80

### :nut_and_bolt: Description: What code changed, and why?

In compliance trend graph the data was getting loop into 377 times with a 10 object arrays and for one year data is looping 13k times with an array of 365 objects that leads to page crash.

### :chains: Related Resources
https://github.com/chef/automate/issues/4353 
### :+1: Definition of Done
 The issue is solved by loop data only once, adding some condition and storing data globally in that particular component 

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable

2020-12-16 18:06 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +      console.log("trendDataCache..!")
remove leftover console log

2020-12-16 18:57 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +  treandDataCache = [];
nit: spelling --> `trendDataCache`

2020-12-16 18:57 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    if(this.treandDataCache === undefined || this.treandDataCache.length == 0) {
nit: spelling --> `trendDataCache`

2020-12-16 18:57 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +      this.treandDataCache = this.data.map(d => {
nit: spelling --> `trendDataCache`

2020-12-16 18:57 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    return this.treandDataCache
nit: spelling --> `trendDataCache`

2020-12-16 18:57 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    this.treandDataCache = [];
nit: spelling --> `trendDataCache`

2020-12-16 19:51 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    return this.treandDataCache
missing semicolon
```suggestion
    return this.treandDataCache;
```

running `make lint` in your terminal while in `components/automate-ui` will do a full lint check and show you any linting issues to fix

2020-12-16 20:00 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> -    }
Why are we removing this fallback?

2020-12-16 20:02 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    const utcDate = moment(time);
```suggestion
    const utcDate = moment.utc(time);
```
We still need to make sure this time is coming back in UTC format.  This is the same as `moment(time).utc()` but a little cleaner to read in my opinion

2020-12-16 20:16 UTC, SEAjamieD commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
>    }
This is a creative approach - and simple, I like that.  I wonder if this might be a candidate for ChangeDetectionStrategy or if that would be overkill.  I found a similar question on stack overflow and it got me thinking if any of the other getters are acting like this.  It doesn't appear to me that they are, but worth looking at: https://stackoverflow.com/questions/40810807/why-does-this-method-gettor-get-called-x-times-in-an-angular-2-service

2020-12-16 20:19 UTC, SEAjamieD requested changes
This is working as it should now, and with a pretty simple solution.  I like it.  I added some thoughts on that in the code. 

Aside from those thoughts, there is a little bit of cleanup to do.  Thanks for all the work on this 🎉

2020-12-17 03:12 UTC, msorens commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
>    }
@SEAjamieD great comment here! Modifying the ChangeDetectionStrategy would indeed be a good fix; it is not overkill.

Another approach, though, is to use the "declared properties" approach I discuss in https://github.com/chef/automate/pull/3810 (in the section labeled "PR bonus"). In a nutshell, that would eliminate the function call to trendData: declare it as a property instead of a getter. Then, observe when it needs to be recalculated--that is just when `this.data` changes. Since that is an `@Input`, you would only need to do a single recalculation of trendData in `ngOnChanges`.

2020-12-17 03:15 UTC, msorens requested changes

2020-12-17 03:15 UTC, msorens commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
>    get domainX() {
Outside the scope of your task here, I would urge you to examine every getter in this file to see which could be changed to private like this. I checked about 10 and every single one should be private.
```suggestion
  private get domainX() {
```

2020-12-21 01:13 UTC, msorens commented on components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
> +    if(this.treandDataCache === undefined || this.treandDataCache.length == 0) {
Changed this back to "unresolved"; still needs to be done.

2020-12-21 01:17 UTC, msorens commented
Please fill out the "How to Build and Test the Change" section in the PR preamble. That is vital for reviewers to adequately and effectively test your code. Note that this will not be the same steps given in the original issue (#4353). You need to explain how to test in dev rather than acceptance, which includes how to get sufficient data in the system to observe the problem (or lack of it). Thanks!!

2020-12-21 18:12 UTC, shaik80 commented
### Before

The page used to crash when we select the option **Last year/Last 3 month** from the dropdown present in the trend graph, every time we call `this.trendData` it uses to loop through each data present in `this.data`

In `get trendData()` we try to convert time which is in type string (**2020-09-21T23:59:59Z**) to type object (**Mon Sep 21 2020 00:00:00 GMT+0530 (India Standard Time)**)

Eg:- To draw a graph in d3 we are calling trendData 377 time’s ( I saw this when I console log in get tendData() ) for 10 day’s graph call is **377 * 10 = 3,770** and for one year data is **377 * 366 = 1,37,982** 

### After

We try to loop only once and Cache in trendDataCache
So that we don’t have to loop once again (from second time onwards, so we are avoiding to loop 366 Times)

Eg:- if trendDataCache is equal to Zero/no data is present in trendDataCache only then we try to convert time which is in type string (**2020-09-21T23:59:59Z**) to type object (**Mon Sep 21 2020 00:00:00 GMT+0530 (India Standard Time)**). Fro second time we can make use of trendDataCache without looking through

To draw a graph in d3 we are calling trendData one time for 10 day’s graph call is **1 * 10 = 10** and for one year data is **1 * 366 = 366** 

2021-01-06 16:48 UTC, kmacgugan approved these changes
Looks good 
![tenor-92331990](https://user-images.githubusercontent.com/11166450/103796304-e27a8d00-4ffb-11eb-8012-08a860c5c204.gif)

2021-01-07 16:37 UTC, msorens approved these changes

2021-01-08 18:22 UTC, merged