[infra-proxy-service] Roles list API bug fixes
chef/automate pull request #4621
Opened 2021-01-22 10:26 UTC by vsingh-msys

### :nut_and_bolt: Description: What code changed, and why?

- Fixes the role list API by counting the length of rows instead of accessing the total from resultset.
- Remove the Role struct from roles.go and considered the role struct after `EnvRunList` got added. [`ac86f72` (#180)](https://github.com/go-chef/chef/pull/180/commits/ac86f72cf00f081ea5db6ae494278dea4a4a4bce)

### :chains: Related Resources
Fixes: #4619

### :+1: Definition of Done

- Fixes role list API failing for some chef server data.

### :athletic_shoe: How to Build and Test the Change
- `rebuild components/infra-proxy-service`
- `rebuild components/automate-gateway`

Steps to test:

- To add data using 3rd internal steps https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views

- Roles list API:

```
curl -sSkH "api-token: $(get_admin_token)" https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/roles?pretty
{
  "roles": [
    {
      "name": "chef-client-update",
      "description": "",
      "environments": [
        "_default"
      ]
    },
    {
      "name": "web-server",
      "description": "",
      "environments": [
        "_default"
      ]
    }
  ]
}
```

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

2021-01-22 10:29 UTC, vsingh-msys commented on components/infra-proxy-service/server/roles.go
> +	cl := make([]*response.RoleListItem, len(result.Rows))
Observe inconsistency in chef server data:
```
knife raw /search/role
{
  "total": 4,
  "start": 0,
  "rows": [

  ]
}
```
To fix this calculating the rows length.

2021-01-22 14:44 UTC, kalroy commented on components/infra-proxy-service/server/roles.go
>  // EnvRunList represents the recipes and roles with environment specified for a node or as part of a role.
RunList and EnvRunList are defined under chef package. We may not need to redefine it here and refer the type defined in chef package.

2021-01-25 05:57 UTC, kalroy requested changes
Added some feedbacks to look into.

2021-01-25 05:58 UTC, vsingh-msys commented on components/infra-proxy-service/server/roles.go
>  type EnvRunList map[string]RunList
yeah, thanks!

2021-01-28 11:37 UTC, vivekshankar1 approved these changes

2021-01-29 15:31 UTC, kalroy approved these changes
Good job. Thank you!! 👏

2021-01-30 00:44 UTC, msorens requested changes
Was going to suggest there should be a unit test to prove this change, but roles.go does not have any unit tests at all; please add.

2021-02-05 06:58 UTC, vsingh-msys commented
This issue due to chef infra server corrupted data, fixes by `chef-server-ctl reindex`, Also list will be changing by search API in PR https://github.com/chef/automate/pull/4658

2021-02-05 06:58 UTC, closed without merging