[WIP][infra-proxy-service] API to update node attributes
chef/automate pull request #4622
Opened 2021-01-22 10:41 UTC by vsingh-msys

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change
- `rebuild components/infra-proxy-service`
- `rebuild components/automate-gateway`

Steps to test:

- To add data using 3rd internal steps https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

2021-01-28 04:25 UTC, msorens commented on components/infra-proxy-service/server/nodes.go
> +// UpdateNode update the node
```suggestion
// UpdateNode updates the node
```

2021-01-28 04:25 UTC, msorens commented on components/infra-proxy-service/server/nodes.go
> +// UpdateNodeAttributes update the node attributes
```suggestion
// UpdateNodeAttributes updates the node attributes
```

2021-01-28 04:25 UTC, msorens commented on components/infra-proxy-service/server/nodes.go
>  // fetchAffectedNodes get the nodes used by chef object
```suggestion
// fetchAffectedNodes gets the nodes used by chef objects
```

2021-03-31 15:51 UTC, punitmundra requested changes
not able to test as per given instructions.

2021-04-01 02:34 UTC, vsingh-msys commented
> not able to test as per given instructions.

@punitmundra could you please elaborate it more.

I followed the same steps to test it out

- git checkout/fetch VSingh/infra-proxy-service-node-update-attribute
- running hab command if not already
- rebuild components/automate-gateway
- rebuild components/automate-gateway
- curl -sSkH "api-token: $(get_admin_token)" -X PUT https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/nodes/aix-7.1/attributes?pretty -d '{"attributes": { "attr1": "abc"}}'


Providing error messages or command running would be helpful?

2021-04-01 06:18 UTC, punitmundra commented
> > not able to test as per given instructions.
> 
> @punitmundra could you please elaborate it more.
> 
> I followed the same steps to test it out
> 
> * git checkout/fetch VSingh/infra-proxy-service-node-update-attribute
> * running hab command if not already
> * rebuild components/automate-gateway
> * rebuild components/infra-proxy-service
> * curl -sSkH "api-token: $(get_admin_token)" -X PUT https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/nodes/aix-7.1/attributes?pretty -d '{"attributes": { "attr1": "abc"}}'
> 
> Providing error messages or command running would be helpful?

@vsingh-msys : how to add the node, that step i am not clear.

2021-04-01 06:26 UTC, vsingh-msys commented
@punitmundra Adding node directly from API is not in scope, nodes getting added into chef-server when a node gets bootstraps. Some of the updates operations allowed like node environment, node attributes, node run list, and reset node key.

2021-04-05 13:07 UTC, punitmundra approved these changes
change are fine. i have tested. code looks fine to me.

2021-04-06 01:28 UTC, kalroy approved these changes

2021-04-06 01:29 UTC, merged