[WIP][infra-proxy-service] break data bag and data bag item APIs
chef/automate pull request #4662
Opened 2021-01-28 09:54 UTC by vsingh-msys

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources
Fixes: #4629 

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

2021-01-28 23:43 UTC, kmacgugan commented
The code looks good to me. I had a few questions and don't have full context on the previous implementations so maybe you could fill me in. I know some databags might have sensitive information like passwords, are we doing any screening on that? Maybe the screening happens in chef-server? For encypted databags I imagine we just store the encypted payload since the data is stored as raw item data, do we have any methods for decrypting those?

2021-01-29 03:44 UTC, vsingh-msys commented
@kmacgugan At present, the existing chef-manage interface does not support viewing encrypted data bag, the only way we can view it using `bundle exec knife data bag show passwords root --secret SECRET`. 

After we will complete with chef manage parity read-only views release, surely we can think of viewing encrypted data bag from Automate UI.

Thanks!

2021-01-29 16:41 UTC, kmacgugan requested changes
Is there any integration tests for infra-proxy-service calls? Some more test coverage would be good here.

2021-02-12 13:49 UTC, kalroy approved these changes

2021-02-12 13:52 UTC, merged