Added UI improvements for server and org list.
chef/automate pull request #4718
Opened 2021-02-11 11:15 UTC by himanshi-chhabra

Signed-off-by: Himanshi Chhabra <himanshi.chhabra@msystechnologies.com>

### :nut_and_bolt: Description: What code changed, and why?
new UI for the Server and Orgs list pages for read-only views 

### :chains: Related Resources
#4713 
### :+1: Definition of Done
1. Removed the border of the Server and org List Table.
2. Added the background colour for Active option.
3. Increased the height of the selected Active Blue Line.
4. Aligned Create Buttons to Right of Server and org.
### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
![orgTab](https://user-images.githubusercontent.com/61003053/107629609-645b7700-6c88-11eb-9a9a-b4703aeccf76.png)
![serverTab](https://user-images.githubusercontent.com/61003053/107629613-658ca400-6c88-11eb-93fd-6011f4bef4e8.png)

2021-02-11 11:49 UTC, vinay033 approved these changes
changes look good to me.

2021-02-11 14:14 UTC, shaik80 approved these changes

2021-02-11 14:14 UTC, shaik80 commented on components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html
>              </chef-tr>
can we follow either Kebab case  or snake case. Kebab case will be best because we are using same pattern in other place

2021-02-11 14:16 UTC, shaik80 requested changes

2021-02-11 14:16 UTC, shaik80 commented on components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html
> +                <chef-th class="three-dot-column no_border_th"></chef-th>
can we follow either Kebab case or snake case. Kebab case will be best because we are using same pattern in other places

2021-02-12 11:19 UTC, shaik80 approved these changes

2021-02-15 04:08 UTC, merged

2021-02-19 13:45 UTC, chaitali-mane commented
Some styling issue found while testing like padding, spacing, alignment .

2021-02-22 13:24 UTC, chaitali-mane commented
Created issue for the UI chages #4749 and raised PR with changes ##4754 against issue.