Show the description column on environment tab
chef/automate pull request #4722
Opened 2021-02-12 11:29 UTC by vinay033

Signed-off-by: Vinay Sharma <vsharma@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
we need to add a description column on the infra proxy environment tab.

![needDesc](https://user-images.githubusercontent.com/12297653/107762451-0c3d7700-6d53-11eb-9288-120bd8b4e0a6.png)

### :chains: Related Resources
https://github.com/chef/automate/issues/4721
### :+1: Definition of Done
I have added changes to show the description column on the environment tab
### :information_source: Note
This PR is not containing the new design CSS, it depends on PR: https://github.com/chef/automate/pull/4673
after merging the dependent PR this page show like same as the attached screenshot.
### :athletic_shoe: How to Build and Test the Change
Steps to reproduce the behavior:
if you have sample data for the infra servers than
go to >> infrastructure tab >> click on Chef server on left side navigation bar >> Organizations >> Environments tab >> see the list of environments.
### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
![Description](https://user-images.githubusercontent.com/12297653/107762460-0fd0fe00-6d53-11eb-9d24-c9a5fdd52c75.png)

2021-02-12 12:11 UTC, shaik80 commented
<img width="1017" alt="Screenshot 2021-02-12 at 5 40 37 PM" src="https://user-images.githubusercontent.com/47217471/107766408-6e997600-6d59-11eb-8eb5-3201d7a9c550.png">
Not able to view description data

2021-02-12 14:25 UTC, vinay033 commented
> <img alt="Screenshot 2021-02-12 at 5 40 37 PM" width="1017" src="https://user-images.githubusercontent.com/47217471/107766408-6e997600-6d59-11eb-8eb5-3201d7a9c550.png">
> 
> Not able to view description data tried to rebuild infra-proxy-service getting the same result to me

have you checked on manage, if manage has a description available for a particular environment then the same data reflecting on automate.

2021-02-15 01:51 UTC, kalroy requested changes

2021-02-15 01:51 UTC, kalroy commented on components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.html
> +            {{ environment.description }}
With long description the text is getting wrapped although we have enough space to the right. 
![image](https://user-images.githubusercontent.com/7055118/107897091-429b1200-6f5e-11eb-8149-3a48a87af035.png)
Is this how the text should look like?

2021-02-15 07:00 UTC, shaik80 approved these changes

2021-02-15 07:07 UTC, shaik80 commented
**👟 How to Build and Test the Change**
Need to rebuild gateway, UI, infra-proxy before testing UI changes

2021-02-17 10:53 UTC, merged