[Read only] Infra node list page UI with search and pagination.
chef/automate pull request #5018
Opened 2021-04-30 11:45 UTC by vinay033

### :nut_and_bolt: Description: What code changed, and why?
We need to add the read-only node list page UI with the search and pagination.

### :chains: Related Resources
https://github.com/chef/automate/issues/4371
### :+1: Definition of Done
I have added the new UI for the infra node list page UI (read-only), I have covered below mentioned points.

- Infra node list page
- Infra node list with pagination
- Search infra nodes
- Cypress specs

### :athletic_shoe: How to Build and Test the Change
```
STEP 1
inside the hab studio

[default:/src:0]# build components/automate-ui-devproxy/
[default:/src:0]# start_automate_ui_background
[default:/src:0]# start_all_services

STEP 2
open new window
go to automate UI path

$ cd components/automate-ui
and run the command 

npm run serve:hab

navigate to `https://a2-dev.test/infrastructure/chef-servers`
add some sample data and then test the changes using tab change
```
To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views

```
Go to the -->  `infrastructure tab` from the top navigation bar then you can see the `Chef Infra Server`
If you have data then you can see the list of servers 
--> then click to any of the servers --> see the list of org's
--> click to any of org ---> you can see the multiple tabs --> default tab is cookbooks tab 
--> you can see the nodes tab ---> click to nodes tab
--> if nodes are available then you can see the list of nodes with search and pagination.
```
### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

https://user-images.githubusercontent.com/12297653/116690675-5d1a4e80-a9d7-11eb-87db-f98beb0cc078.mp4

2021-04-30 15:02 UTC, himanshi-chhabra requested changes

2021-04-30 15:02 UTC, himanshi-chhabra commented on components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.html
> +  <app-empty-state *ngIf="authFailure" moduleTitle="roles" (resetKeyRedirection)="resetKeyTabRedirection($event)">
I guess modulTitle should be equal to "nodes"?

2021-05-03 10:51 UTC, himanshi-chhabra approved these changes
LGTM

2021-05-03 18:40 UTC, SEAjamieD approved these changes
Really great job on this 🎉  - my only request would be more unit tests if/when you have the time.

2021-05-04 11:14 UTC, merged