Details of the Node
chef/automate pull request #5101
Opened 2021-05-25 07:37 UTC by dishanktiwari2501

Signed-off-by: Dishank Tiwari <dtiwari@progress.com>

**DO NOT REVIEW RIGHT NOW (THIS IS INCOMPLETE PR, CREATED JUST TO TRACK)**

The Details section has been added to the Node object of Chef Infra Server.

2021-05-26 09:17 UTC, vinay033 approved these changes
LGTM

2021-05-27 22:06 UTC, kagarmoe requested changes

2021-05-27 22:06 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +The next section of the page is the details section to view or update the node environment. The drop down menu consists of the list of environment created in the chef server. You can select any one e
```suggestion
The **Details** section of the Single Node page lets you modify a node's information by changing its environment or adding and removing tags.
```

2021-05-27 22:06 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +To select the environment:
```suggestion
To change the environment:
```

2021-05-27 22:06 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +- Click on the dropdown menu and select the name of the environment.
```suggestion
- Select the dropdown menu and choose the name of the environment.
```

2021-05-27 22:06 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +- You can add tags to the environment from the text bar below the dropdown menu.
```suggestion
- Add tags to the environment from the text bar below the dropdown menu.
```

2021-06-01 08:52 UTC, merged