Vivek shankar/fixed extra node addded azure api
chef/automate pull request #5290
Opened 2021-06-25 10:11 UTC by vivekshankar1

### :nut_and_bolt: Description: What code changed, and why?

Fixed issue where extra node was being added after every azure-api scan

### :chains: Related Resources

### :+1: Definition of Done

Extra nodes should not be added after every azure API scan. Number of nodes must remain same

### :athletic_shoe: How to Build and Test the Change

- rebuild components/nodemanager-service

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

2021-06-25 10:29 UTC, vivek-yadav approved these changes

2021-06-27 17:51 UTC, kalroy requested changes
Although the issue is fixed, check the review comments.

2021-06-28 13:50 UTC, vivekshankar1 commented on components/nodemanager-service/pgdb/filtering.go
> +	seen := make(map[string]struct{})
I have made the requested changes.

2021-06-28 13:50 UTC, vivekshankar1 commented on components/nodemanager-service/pgdb/filtering.go
> +	b := a[:0]
I have made the requested changes.

2021-06-28 13:50 UTC, vivekshankar1 commented on components/nodemanager-service/pgdb/filtering.go
> +		if item == "" {
No there is no performance concern as coalesce is more like a case. I have made the requested changes.

2021-06-28 13:51 UTC, vivekshankar1 commented on components/nodemanager-service/pgdb/filtering.go
> +			condition += ")"
removed it as not required any more after coalesce

2021-06-28 13:51 UTC, vivekshankar1 commented on components/nodemanager-service/pgdb/filtering.go
> +	condition += ")"
removed it as not required any more after coalesce

2021-06-29 14:53 UTC, vivek-yadav approved these changes

2021-06-29 16:05 UTC, kalroy approved these changes

2021-06-29 16:05 UTC, merged