[infra-proxy-service] GET policy group details API
chef/automate pull request #5361
Opened 2021-07-16 07:07 UTC by vinay033

Signed-off-by: Vinay Sharma <vsharma@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
Need to add the backend API to fetch the details of the policy group.

### :chains: Related Resources
https://github.com/chef/automate/issues/5346
### :+1: Definition of Done
 -  I have added API to fetch the details of the policy group.
 
### :athletic_shoe: How to Build and Test the Change
Steps to build:
```
rebuild components/infra-proxy-service
rebuild components/automate-gateway
```
if you don't have sample data then you need to add first
1.  Ensure Chef Infra Server is running. If it is not start it with `start_chef_server`
2. First you need to run the `infra_service_load_chef_repo`
3. Then run `load_policy_files_sample_data`

Steps to test:

Add the chef-server test environment credentials and extract the SERVER and ORG IDs.
Policy group details API - 
request 
```
curl -sSkH "api-token: $(get_admin_token)"  https://a2-dev.test/api/v0/infra/servers/SERVER/orgs/ORG/policygroups/NAME
```
response 
```
{
    "name":"test_policy_group",
    "policies":
    [
        {
            "name":"vinay-dev",
            "revision_id":"24a6c87fbe5359b5191cc866ce969020f8050332ac94b6a2349ca71682f619f5"
        }, 
        { 
            "name":"examplecb", 
            "revision_id":"c1ff74007ae1c19f848802c517f0167b0eeaeecc7907a8a24b2c99edaabda538"
        }
    ],
    "uri":"https://a2-dev.test/organizations/test/policy_groups/test_policy_group"
}
```

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-07-23 20:48 UTC, rickmarry approved these changes
thank you @vinay033!

2021-07-24 04:55 UTC, kalroy approved these changes
LGTM

2021-07-24 05:05 UTC, kalroy requested changes
Run `make lint` on gateway and infra-proxy-service folder. The files are not properly formatted

2021-07-26 14:23 UTC, kalroy approved these changes

2021-07-26 15:56 UTC, merged