Generation of new HA config for A2HA inside automate <#5401>
chef/automate pull request #5478
Opened 2021-08-11 13:37 UTC by jayvikramsharma1

### :nut_and_bolt: Description: What code changed, and why?
As per requirement we need to generate a wrapper config file for automate HA mode deployment
It contains two type of HA mode deployment either AWS or Existing Nodes, base on argument with init-config-ha command

- **chef-automate init-config-ha existing_node**
- **chef-automate init-config-ha aws**

### :chains: Related Resources
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5401
### :+1: Definition of Done
Written code for generating config.toml file as a first phase, Unit Test cases covered, devevloper testing of acceptance criteria and working behaviour.
### :athletic_shoe: How to Build and Test the Change

- **rebuild components/automate-cli/**
 
### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-08-11 13:54 UTC, punitmundra approved these changes
changes looks to fine.

2021-08-11 15:08 UTC, karunesh-tech approved these changes

2021-08-12 14:31 UTC, kalroy requested changes

2021-08-13 05:53 UTC, punitmundra commented on components/automate-cli/cmd/chef-automate/init_config_ha.go
> +	} else if args[0] == "existing_node" {
bare-metal

2021-08-18 13:15 UTC, jayvikramsharma1 commented
@kalroy @punitmundra Please review my PR, I have done review changes

2021-08-18 15:36 UTC, kalroy approved these changes

2021-08-18 15:37 UTC, kalroy commented
Code changes look good. But please fix the pipeline before merging.

2021-08-19 07:29 UTC, merged