Session Timeout feature in Chef Automate
chef/automate pull request #5627
Opened 2021-08-30 11:30 UTC by dishanktiwari2501

Signed-off-by: Dishank Tiwari <dtiwari@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

- Automate UI checks for user activities such as mouse movement, click, keyboard keypress, scroll, etc.
- If there is no activity from the user's side for the time specified for idle_timeout_minutes in config.toml then the user will be
explicitly logged out.
- This feature can be enabled/disabled by enable_idle_timeout this property in config.toml

### :chains: Related Resources

- https://github.com/chef/automate/issues/5381
- https://github.com/chef/automate/issues/5072

### :+1: Definition of Done

Added a new page named **Session Timeout** under **Configure** section of Chef Automate.

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

2021-09-01 08:25 UTC, Abdul-Az approved these changes
We could also mention a point stating minimum time for idle_timeout_minutes should be 5 minutes or above.

2021-09-01 09:58 UTC, kalroy requested changes
While testing I found this error: 
```
Start building sites …
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: "/Users/karoy/Projects/automate/components/docs-chef-io/content/automate/chef_infra_server.md:166:112": failed to extract shortcode: template for shortcode "fontawesome" not found
Built in 966 ms
make: *** [serve] Error 255
```

2021-09-01 09:58 UTC, kalroy commented on components/docs-chef-io/content/automate/session_timeout.md
> +- Set the value of `idle_time_minutes` property to your desired time in minutes(for example **30**). (Setting the value of this property to **30** will set the session timeout time to 30 minutes).
It should be `idle_timeout_minutes`. 
The `idle_timeout_minutes` should be more than 5 minutes

2021-09-02 07:04 UTC, kalroy approved these changes

2021-09-02 07:04 UTC, merged