[infra-proxy-service] User management - GET Server users list API
chef/automate pull request #5636
Opened 2021-08-31 14:29 UTC by sonali523

### :nut_and_bolt: Description: What code changed, and why?
List the users in a server

### :chains: Related Resources
https://github.com/chef/automate/issues/5554

### :+1: Definition of Done
I have added API to list the users in a server

### :athletic_shoe: How to Build and Test the Change
Steps to build:
```
rebuild components/infra-proxy-service
rebuild components/automate-gateway
```
Steps to test:

1. Ensure Chef Infra Server is running. If it is not start it with ```start_chef_server```
2. Add the chef-server test environment credentials and extract the SERVER IDs
3. Add the server admin name and admin key in the request body

Request

```curl -sSkH "api-token: $(get_admin_token)" 'https://a2-dev.test/api/v0/infra/servers/SERVER_ID/users'```

request body
```
{
    "admin_name":"ADMIN_NAME",
    "admin_key":"ADMIN_KEY"
}
```

Response

```
{
    "users": [
       {
            "username": "sonali",
            "first_name": "Sonali",
            "last_name": "Wale",
            "email": "swale@progress.com"
        },
        {
            "username": "vinay",
            "first_name": "Vinay",
            "last_name": "Sharma",
            "email": "vsharma@chef.io"
        }
    ]
}
```

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-08-31 16:02 UTC, kalroy requested changes

2021-08-31 16:02 UTC, kalroy commented on components/infra-proxy-service/server/proxy.go
> +func (s *Server) createChefClient(ctx context.Context, serverID string, adminkey string, adminName string) (*ChefClient, error) {
Rename it as `createChefServerClient`

2021-09-01 13:16 UTC, sonali523 commented on api/external/infra_proxy/response/users.proto
> +message ServerUserListItem {
Updated the changes, please review

2021-09-01 13:17 UTC, sonali523 commented on api/interservice/infra_proxy/response/users.proto
> +message ServerUserListItem {
Did the suggested changes

2021-09-01 13:19 UTC, sonali523 commented on components/infra-proxy-service/server/proxy.go
> +func (s *Server) createChefClient(ctx context.Context, serverID string, adminkey string, adminName string) (*ChefClient, error) {
renamed to ```createChefServerClient```

2021-09-01 14:21 UTC, vinay033 approved these changes

2021-09-02 06:09 UTC, kalroy approved these changes

2021-09-02 08:59 UTC, merged