5503 a2ha command mapping
chef/automate pull request #5645
Opened 2021-09-01 19:32 UTC by jayvikramsharma1

### :nut_and_bolt: Description: What code changed, and why?

Mapping of Workspace, secrets, help command in automate from A2HA

### :chains: Related Resources

https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5503

### :+1: Definition of Done

written codes, done developer testing of commands

### :athletic_shoe: How to Build and Test the Change

rebuild components/automate-cli/

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-21 11:40 UTC, kalroy requested changes

2021-09-21 11:40 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/secrets-ha-template.go
> +	be_sudo_password				Set different sudo password for bacend machines
spelling mistake -- `should be backend`

2021-09-21 11:40 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/secrets-ha-template.go
> +    set                              Add a new secrets: for more info use 'secrets set --help'
Should be `a new secret`

2021-09-21 11:40 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/secrets-ha-template.go
> +    delete                           Delete existing secrets: for more info use 'secrets delete --help'
Can we delete multiple secrets? If no, should be `Delete an existing secret`

2021-09-21 11:48 UTC, kalroy requested changes

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/secrets-ha.go
> +	Short: "set secrets to automate HA",
```suggestion
	Short: "Set secrets to automate HA",
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/secrets-ha.go
> +	Long:  "set secrets for automate sudo password and admin password in HA mode.",
```suggestion
	Long:  "Set secrets for automate sudo password and admin password in HA mode.",
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha-template.go
> +    -h, --help                       print help
```suggestion
    -h, --help                       Print help
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha-template.go
> +    SUBCOMMAND                       subcommand
```suggestion
    SUBCOMMAND                       Subcommand
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha-template.go
> +    [ARG] ...                        subcommand arguments
```suggestion
    [ARG] ...                        Subcommand arguments
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha.go
> +	Short: "set workspace env for automate HA.",
```suggestion
	Short: "Set workspace env for automate HA.",
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha.go
> +	Long:  "set up automate ha cluster workspace.",
```suggestion
	Long:  "Set up automate ha cluster workspace.",
```

2021-09-21 11:48 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/workspace-ha.go
> +	writer.Printf("setting automate HA cluster workspace \n")
```suggestion
	writer.Printf("Setting automate HA cluster workspace \n")
```

2021-09-22 06:21 UTC, vivek-yadav approved these changes

2021-12-02 11:00 UTC, closed without merging