Chef Infra Server Updates
chef/automate pull request #5678
Opened 2021-09-07 12:29 UTC by dishanktiwari2501

DO NOT REVIEW NOW

### :nut_and_bolt: Description: What code changed, and why?

- Policyfiles tab under Policy Group
- Nodes tab under Policy Group
- Pagination in Policy Group
- Slider added for the specific Cookbooks
- Runlist tab added for the Policyfiles section

### :chains: Related Resources

- https://github.com/chef/automate/pull/5498
- https://github.com/chef/automate/pull/5630
- https://github.com/chef/automate/pull/5640
- https://github.com/chef/automate/pull/5553
- https://github.com/chef/automate/pull/5619

### :+1: Definition of Done

All the above changes have been made to the Chef Infra Server Page

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-07 19:51 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +Select the **Cookbook Dependencies** button to view all the *Dependencies Rules* and *Cookbook* of the policyfile in table format. Select a specific cookbook from the list to view the details of the
If these should be italics, then please use the _ (underscore). Yes, I know that both work, but the underscore lets us know your intent.

2021-09-07 20:00 UTC, kagarmoe requested changes
Small changes & we're diagnosing the build failures.

2021-09-07 20:16 UTC, kagarmoe commented
💥 Fixed the netlify problem.

2021-09-15 14:09 UTC, himanshi-chhabra approved these changes

2021-09-17 21:04 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +The **Content** tab contains the list of all:
```suggestion
The **Content** tab lists the:
```

2021-09-17 21:04 UTC, kagarmoe commented on components/docs-chef-io/content/automate/chef_infra_server.md
> +Select a specific Policyfile from the _Included Policies_ to view the details.
```suggestion
Select a Policyfile from the _Included Policies_ to view the details.
```

2021-09-22 19:00 UTC, kagarmoe approved these changes
![tenor-195940184](https://user-images.githubusercontent.com/4400151/134405291-48a9f25c-0bd9-491f-a67a-bd39f6ff01b0.gif)

2021-09-28 11:18 UTC, merged