Command mapping 5502 1
chef/automate pull request #5699
Opened 2021-09-09 10:40 UTC by jayvikramsharma1

### :nut_and_bolt: Description: What code changed, and why?
command mapping for following commands
**gather-logs --> chef-automate gather-logs
status --> chef-automate status
test --> chef-automate status**

### :chains: Related Resources

https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5502

### :+1: Definition of Done

Dev Done, coding and dev manual testing

### :athletic_shoe: How to Build and Test the Change

rebuild component/automate-cli

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-16 09:48 UTC, punitmundra approved these changes
just change the one of the logs -> A2HA Cluster status. rest every thing is ok. 
Add in the desc...that a2ha gather-logs only work ...when we have deployed cluster.

2021-09-16 09:48 UTC, punitmundra commented on components/automate-cli/cmd/chef-automate/status-ha.go
> +	writer.Printf("getting status \n")
getting status -> A2HA Cluster Status

2021-09-21 11:46 UTC, kalroy requested changes

2021-09-21 11:46 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/gather-logs-ha-template.go
> +    -n, --log-lines NUMBER             How many journalctl lines to capture
journalctl is a command. Are we trying to capture the command output or the contents of journal logs?

2021-09-21 11:46 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/gather-logs-ha-template.go
> +    -h, --help                         print help
```suggestion
    -h, --help                         Print help
```

2021-09-21 11:46 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/gather-logs-ha-template.go
> +    -c, --config-file CONFIG_FILE      Load settings from config file (default: "/root/workspace/a2-ha-backend/a2ha.rb")
Is it `/root` or `/hab` @punitmundra ?

2021-09-21 11:46 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/statusHaHelpDoc.go
> +	shows status of services running.
If it is across all the nodes better to mention that.

2021-09-21 11:46 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/status.go
> +		getStatus := func() (*api.StatusResponse, error) {
Are these tabs? If so please convert to whitespaces

2021-09-23 07:19 UTC, vivek-yadav commented on components/automate-cli/cmd/chef-automate/gather-logs.go
> +	} else {
removing Else will make the flow simple, also diff will be smaller.

2021-09-23 07:20 UTC, vivek-yadav commented on components/automate-cli/cmd/chef-automate/status.go
> +	} else {
Same here, if Else is remove the flow will be simple, and diff will be smaller

2021-09-23 07:23 UTC, vivek-yadav commented on components/automate-cli/cmd/chef-automate/testHA.go
> +	} else {
same here, Else is not needed.

2021-12-02 10:59 UTC, closed without merging