ELK integration
chef/automate pull request #5714
Opened 2021-09-14 05:26 UTC by shaik80

Signed-off-by: shaik80 <shaik.mudassir@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-14 07:52 UTC, vivekshankar1 requested changes
Please add unit test cases for saveDestination, testDestination and validateForm for elk. In cypress please add test case for test failure

2021-09-15 17:32 UTC, vivek-yadav commented on components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.html
> +            <div class="overlay" *ngIf="item.name !== 'ServiceNow' && item.name !== 'Splunk' && item.name !== 'ELK'">
can we have this validation in a function ?

2021-09-17 05:21 UTC, MadhviAtroliya commented on components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.spec.ts
> +    });
Put some spaces between two test cases.

2021-09-17 05:24 UTC, MadhviAtroliya commented on components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.ts
> +        this.authSelected = AuthTypes.USERNAMEANDPASSWORD;
In story ELK page open with default authentication as Access token, is this ok to show with Username and password?

2021-09-17 05:25 UTC, MadhviAtroliya commented on e2e/cypress/integration/ui/settings/data-feed/data-feed-create.spec.ts
> +    it('create data feed error splunk', () => {
Give space between two different test cases

2021-09-17 07:29 UTC, MadhviAtroliya approved these changes

2021-09-17 07:36 UTC, shivangi-singh1 approved these changes

2021-09-17 07:49 UTC, vivekshankar1 approved these changes
Thanks shaik, its working properly

2021-09-20 13:19 UTC, vivek-yadav approved these changes

2021-09-20 14:36 UTC, merged