Adding info and ssh commands to automate-cli
chef/automate pull request #5716
Opened 2021-09-14 07:58 UTC by FaizanSRE

Signed-off-by: FaizanSRE <ffulara@msystechnologies.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-22 06:25 UTC, FaizanSRE commented
@vivek-yadav @kalroy I have added the help information for info command , as discussed yesterday. So now we don't have anything pending, so please have a look and approve it.

2021-09-22 06:31 UTC, kalroy requested changes

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/Ssh-ha-template.go
> +    -h, --help                       print help
```suggestion
    -h, --help                       Print help
```

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/Ssh-ha.go
> +	Short: "set Ssh env for automate HA.",
```suggestion
	Short: "Set Ssh env for automate HA.",
```

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/Ssh-ha.go
> +	Long:  "set up automate ha clusterSsh",
```suggestion
	Long:  "Set up automate ha clusterSsh",
```

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//args = append([]string{"info"})
Remove commented codes

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//writer.Printf("A2HA new secret set. %d, exiting\n", c.Process.Pid)
Remove commented codes

2021-09-22 06:31 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//Args: cobra.RangeArgs(0, 2),
Remove

2021-09-22 07:13 UTC, FaizanSRE commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//Args: cobra.RangeArgs(0, 2),
Done

2021-09-22 07:14 UTC, FaizanSRE commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//writer.Printf("A2HA new secret set. %d, exiting\n", c.Process.Pid)
Done

2021-09-23 04:36 UTC, FaizanSRE commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +	//Args: cobra.RangeArgs(0, 2),
@kalroy Commited all suggested changes, please have a look

2021-09-24 12:36 UTC, kalroy approved these changes

2021-09-30 08:11 UTC, punitmundra approved these changes
rebase with the latest code and make sure that buildkite should passed

2021-10-05 07:42 UTC, merged