Storage functions for users table
chef/automate pull request #5731
Opened 2021-09-15 13:50 UTC by sonali523

### :nut_and_bolt: Description: What code changed, and why?
Storage functions for users table

### :chains: Related Resources
https://github.com/chef/automate/issues/5720

### :+1: Definition of Done
I have added the storage functions for users table

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-09-16 17:23 UTC, kalroy requested changes
Please take care of the coding standards and format the document better

2021-09-17 08:47 UTC, sonali523 commented on components/infra-proxy-service/storage/postgres/users.go
> +func (p *postgres) InsertUser(ctx context.Context, id, serverID, infraServerUsername, credentialID, Connector, automateUserID string, IsServerAdmin bool) (storage.User, error) {
Updated the parameter names, please review

2021-09-17 08:50 UTC, sonali523 commented on components/infra-proxy-service/storage/postgres/users.go
> +		`INSERT INTO users (id, server_id, infra_server_username, credential_id, connector, automate_user_id,is_server_admin,created_at,updated_at)
now() is the postgreSQL function, So used time.Now() function to get the time and did the changes

2021-09-17 10:06 UTC, kalroy approved these changes

2021-09-17 10:56 UTC, merged