Adding initial setup for worker model using cereal service
chef/automate pull request #5894
Opened 2021-10-11 10:38 UTC by Dmaddu

Signed-off-by: Durga Sarat Chandra Maddu <durgasaratchandra.maddu@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

from hab studio
`rebuild components/report-manager-minio-gateway/`
`rebuild components/report-manager-service/`
`rebuild components/automate-cli/`
`rebuild components/automate-deployment/`
`start_all_services`

once all the services are up and running execute below command multiple times say 5 

`chef-automate dev grpcurl report-manager-service -- -d '{"requestor_id":"testID"}' chef.automate.domain.report_manager.service.ReportManagerService.PrepareCustomReport`

each time the command should produce the response something as below 
`{
  "acknowledgementID": "xxxxxxx"
}`

then execute 
`sl | grep report-manager-service`

you should see something like below

`In TaskRun working on job XXXXXX`
`Entered ReportWorkflow > OnTaskComplete with payload`
`successfully completed the task XXXXX`

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-10-13 16:59 UTC, kalroy requested changes
There are a lot of files to review in this PR. Would appreciate if we can smaller PRs to work with.

2021-10-13 16:59 UTC, kalroy commented on api/config/report_manager/config_request.proto
> +        		google.protobuf.StringValue message = 3;
Seems some indentation issue. Buff is going to throw error.

2021-10-13 16:59 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +// GetNodeInfoFromReportID returns report header information of a single report
Why do we need to change the API functions in this PR? Confused

2021-10-13 16:59 UTC, kalroy commented on components/report-manager-minio-gateway/habitat/hooks/run
> +exec minio server \
This will start minio always as a server. How are we going to determine when to start it as a gateway?

2021-10-13 16:59 UTC, kalroy commented on components/report-manager-service/cmd/report-manager-service/report-manager-service.go
> +	time.Sleep(30 * time.Second)
I do not think that's the best way to do it. Can we add a logic to ping and check the status?

2021-10-14 05:41 UTC, Dmaddu commented
@kalroy I rebased this branch, seeing lots of files, and buf failure is because of pushing other PRs to base branch. 
All those should be fixed now. Please review.

2021-10-19 02:22 UTC, merged