Export request API(#5968)
chef/automate pull request #5976
Opened 2021-10-22 02:51 UTC by mchengat88

Signed-off-by: Mansoor <mchengat@msystechnologies.com>

### :nut_and_bolt: Description: What code changed, and why?

New API that accepts the custom export request and returns the corresponding acknowledgement id.
### :chains: Related Resources
https://github.com/chef/automate/issues/5968
### :+1: Definition of Done
Created new API that accepts the custom export request and returns the corresponding acknowledgement id.
### :athletic_shoe: How to Build and Test the Change
clone the changes
rebuild automate-gateway
rebuild compliance-service

```
curl -X POST https://a2-dev.test/api/v0/compliance/reporting/exportv1 -H "X-Data-Collector-Token:xxxxxxx" -d '{"filters":[]}' -k
```
### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-10-31 16:52 UTC, kalroy requested changes

2021-10-31 16:52 UTC, kalroy commented on components/compliance-service/api/reporting/server/server.go
> +		cur, err := srv.es.GetReportManagerRequest(reportIDs.Ids[idx], formattedFilters)
Let's add an issue to avoid sending all the profiles and controls when no filter query is sent

2021-10-31 16:52 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest will retrieve report %s based on filters %+v", reportId, filters)
```suggestion
	logrus.Debugf("%s will retrieve report %s based on filters %+v", method, reportId, filters)
```

2021-10-31 16:52 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest for reportid=%s, filters=%+v", reportId, filters)
```suggestion
	logrus.Debugf("%s for reportid=%s, filters=%+v", method, reportId, filters)
```

2021-10-31 16:52 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	LogQueryPartMin(queryInfo.esIndex, source, "GetReportManagerRequest query searchSource")
same as above

2021-10-31 16:52 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest got %d reports in %d milliseconds\n", searchResult.TotalHits(),
same change as above

2021-11-01 14:04 UTC, Dmaddu commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest will retrieve report %s based on filters %+v", reportId, filters)
Done

2021-11-01 14:04 UTC, Dmaddu commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest got %d reports in %d milliseconds\n", searchResult.TotalHits(),
Done

2021-11-01 14:04 UTC, Dmaddu commented on components/compliance-service/reporting/relaxting/reports.go
> +	logrus.Debugf("GetReportManagerRequest for reportid=%s, filters=%+v", reportId, filters)
Done

2021-11-02 10:53 UTC, kalroy approved these changes

2021-11-02 10:53 UTC, merged