added changes for the update package kind-of: 6.0.3
chef/automate pull request #6064
Opened 2021-11-08 14:34 UTC by sumanprogress

### :nut_and_bolt: Description: What code changed, and why?
We need to Upgrade kind-of: 6.0.3 or later

#

### :chains: Related Resources
#5607

### :+1: Definition of Done
I have updated the Kind-of package version.

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-11-10 04:59 UTC, chaitali-mane commented
@sumanprogress update 'kind-of' package version in package-lock.json, not in package.json

2021-11-15 08:35 UTC, vinay033 commented
@sumanprogress  have you done these changes manually or used the command if you did it manually then do using the command.

2021-11-15 08:35 UTC, vinay033 requested changes

2021-11-15 08:35 UTC, vinay033 commented on components/chef-ui-library/package-lock.json
> +}
add end of line in this file

2021-11-16 07:13 UTC, sumanprogress commented on components/chef-ui-library/package-lock.json
> +}
new line added

2021-11-16 10:57 UTC, chaitali-mane approved these changes

2021-11-17 05:41 UTC, vinay033 approved these changes

2021-11-23 04:27 UTC, merged