API to validate the webui key
chef/automate pull request #6364
Opened 2021-12-13 08:25 UTC by vinay033

### :nut_and_bolt: Description: What code changed, and why?

we need to add one API to validate the webui key for the server.
### :chains: Related Resources
https://github.com/chef/automate/issues/6273
### :+1: Definition of Done
I have added API to validate the webui key.
### :athletic_shoe: How to Build and Test the Change
Steps to build:
```
rebuild components/infra-proxy-service
rebuild components/automate-gateway
```
```
webui key is available for the server - 

curl --location --request POST 'https://a2-dev.test/api/v0/infra/servers/validate' \
--header 'api-token: your admin token' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "id":"chef-server",
    "fqdn":"a2-dev.test",
    "webui_key": "",
    "is_webui_key":true
}'

webui key is not available for the server going to add new one

curl --location --request POST 'https://a2-dev.test/api/v0/infra/servers/validate' \
--header 'api-token: your admin token' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "id":"",
    "fqdn":"a2-dev.test",
    "webui_key": "---webui key----",
    "is_webui_key":false
}'

```
Note: 
in case of is_webui_key - true means webui key is already available for server, if is_webui_key is false means you are going to add new webui key

valid response
```
{
    "valid": true,
    "error": ""
}
```

Invalid response
```
{
    "valid": false,
    "error": "The user or client who made the request could not be authenticated. Verify the user/client name, and that the correct key was used to sign the request."
}
```
### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2021-12-13 18:44 UTC, kalroy requested changes

2021-12-13 18:44 UTC, kalroy commented on api/external/infra_proxy/request/servers.proto
> +    // Chef Server Webui Key
```suggestion
    // Optional Chef Server Webui Key
```

2021-12-13 18:44 UTC, kalroy commented on api/external/infra_proxy/request/servers.proto
> +    bool is_webui_key = 4;
Do not understand the necessity of passing this?

2021-12-13 18:44 UTC, kalroy commented on api/interservice/infra_proxy/request/servers.proto
> +    // Chef Server Webui Key
```suggestion
    // Optional Chef Server Webui Key
```

2021-12-13 18:44 UTC, kalroy commented on api/interservice/infra_proxy/request/servers.proto
> +    bool is_webui_key = 4;
Do not understand the need of passing it as request

2021-12-13 18:44 UTC, kalroy commented on components/automate-gateway/handler/infra_proxy/servers.go
> +		IsWebuiKey: r.IsWebuiKey,
We should pass it as true and no need to get it from request:
```suggestion
		IsWebuiKey: true,
```

2021-12-13 18:44 UTC, kalroy commented on components/infra-proxy-service/server/proxy.go
> +// GetWebuiKeyFrom returns Webuikey
The code is already written `GetOrgAdminKeyFrom`
We need to do this:
- Refactor the code to a common function
- Use the common function in both these functions

2021-12-13 18:44 UTC, kalroy commented on components/infra-proxy-service/server/servers.go
> +	if req.IsWebuiKey && req.Id != "" {
We do not need `req.IsWebuiKey`. We can check `req.WebUIKey` for empty string

2021-12-13 18:44 UTC, kalroy commented on components/infra-proxy-service/server/servers.go
> +		req.WebuiKey = GetWebuiKeyFrom(secret)
Never modify request object.
Declare a local variable in the function to store the passed the WebUIKey and change it

2021-12-13 18:44 UTC, kalroy commented on components/infra-proxy-service/server/servers.go
> +		secret, err := s.service.Secrets.Read(ctx, &secrets.Id{Id: server.CredentialID})
We need to also add another condition to check if the server table has credential_id or not.
If not, we should return false and error

2021-12-13 18:44 UTC, kalroy commented on components/automate-gateway/handler/infra_proxy/servers.go
> +		return nil, err
In case of error we should return the response with false validation

2021-12-15 07:36 UTC, sonali523 commented
While testing, it's observed that sometimes if we change any character in web ui key then also the API is giving 
{
    "valid": true,
    "error": ""
}

2021-12-17 06:26 UTC, kalroy approved these changes

2021-12-17 12:59 UTC, sonali523 approved these changes

2021-12-17 13:08 UTC, merged