Saas/managed services
chef/automate pull request #6606
Opened 2022-01-21 05:40 UTC by shanmugapriya-tr

### :nut_and_bolt: Description: What code changed, and why?

This PR contains changes for skipping the setup of internal Elasticsearch and Postgres in case External ES or PG configuration is enabled. The following changes were made to achieve this : 

- Made automate-elasticsearch an optional dependency in es-sidecar-service
- While building the desired state for deployment, the deployment state of automate-elasticsearch and automate-postgresql services are set to Removed
- While performing Health check, automate-elasticsearch and automate-postgresql services are skipped in case external configuration is set

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ x ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ x ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ x ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ x ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ x ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

### :camera: Screenshots, if applicable

2022-01-31 13:47 UTC, punitmundra commented on components/automate-deployment/pkg/server/server.go
> +		servicesToSkip = append(servicesToSkip, "automate-elasticsearch")
use Const for automate-postgresql and automate-elasticsearch

2022-01-31 13:48 UTC, punitmundra approved these changes
LGTM. just use const instead of stings.

2022-02-02 10:55 UTC, vivek-yadav commented on components/automate-deployment/pkg/server/server.go
> +			if service.Name() == constants.AutomateESService {
move name check to outside

2022-02-02 10:56 UTC, vivek-yadav commented on components/automate-deployment/pkg/server/server.go
> +	servicesToSkip := make([]string, 0, len(serviceList))
can we move this check in a function

2022-02-14 07:18 UTC, shanmugapriya-tr commented
@punitmundra @kalroy @vivek-yadav Please review the updated PR and provide feedback/approval.

2022-02-15 05:48 UTC, punitmundra approved these changes
LGTM

2022-02-21 05:23 UTC, karunesh-tech approved these changes

2022-02-21 05:24 UTC, shanmugapriya-tr commented
@vivek-yadav @kalroy @Dmaddu @rickmarry Please review the updated PR or please provide your approval to the PR.

2022-02-23 08:24 UTC, kalroy requested changes

2022-02-28 04:46 UTC, shanmugapriya-tr commented on components/automate-deployment/pkg/server/server.go
> +			for _, x := range servicesToSkip {
updated to map @kalroy

2022-02-28 04:46 UTC, shanmugapriya-tr commented
@kalroy Have resolved the comments provided. Please review and approve PR

2022-03-02 08:20 UTC, shanmugapriya-tr commented
@kalroy please review the changes and approve.

2022-03-09 12:35 UTC, vivek-yadav commented
Please rebase it one more time, as notification service issue was resolved in main. but here in the pipeline it was still failing.

2022-03-10 07:32 UTC, vivek-yadav approved these changes

2022-03-10 08:14 UTC, shanmugapriya-tr commented
@kalroy @karunesh-tech - I have rebased the branch with main. The build failures are not related to the changes done as a part of this PR. Please approve the PR if it is good to be merged

2022-03-16 05:39 UTC, shanmugapriya-tr commented
@kalroy Please review and approve the PR.

2022-03-16 13:23 UTC, kalroy approved these changes

2022-03-17 07:03 UTC, shanmugapriya-tr commented
@kalroy - Can you please help merging the PR ?

2022-03-18 05:57 UTC, merged