API to fetch the status of the migration
chef/automate pull request #6637
Opened 2022-01-28 14:12 UTC by sonali523

### :nut_and_bolt: Description: What code changed, and why?

Added an API to fetch the status of the latest migration of given migration id
### :chains: Related Resources
https://github.com/chef/automate/issues/6378
### :+1: Definition of Done
I have added an API to fetch the status of the latest migration of given migration id
### :athletic_shoe: How to Build and Test the Change
Steps to build:
```
rebuild components/infra-proxy-service
rebuild components/automate-gateway
```
Steps to test:
Request
```
curl --location --request GET 'https://a2-dev.test/api/v0/infra/servers/migrations/status/MIGRATION_ID' \
--header 'api-token: your admin token'
```
Response
{
    "migration_id": "44d1d571-b108-4c23-82d5-e34b530c96bd",
    "migration_type": "Migration of users",
    "migration_status": "Failed"
}
### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-01-30 15:44 UTC, kalroy approved these changes

2022-01-31 05:50 UTC, YashviJain01 approved these changes

2022-01-31 06:25 UTC, YashviJain01 requested changes

2022-01-31 06:25 UTC, YashviJain01 commented on components/infra-proxy-service/storage/postgres/migrations.go
> +			  and t.id <= 5000 and m.migration_id=$1 order by updated_timestamp desc FETCH FIRST ROW ONLY`
@sonali523  I think we need to change this query, do we need failed and completed status as well??

2022-01-31 06:31 UTC, YashviJain01 approved these changes

2022-01-31 07:12 UTC, YashviJain01 approved these changes

2022-01-31 07:13 UTC, merged