Feature/migration pipe
chef/automate pull request #6647
Opened 2022-01-31 09:43 UTC by dave-augustus

### :nut_and_bolt: Description: What code changed, and why?
Create a Demo pipeline for extraction and parsing of zip file and saving all the required info into the db.

### :chains: Related Resources
Migration Data Service, upload of zip file

https://github.com/chef/automate/issues/6562
https://github.com/chef/automate/issues/6563

### :+1: Definition of Done
Gat a demo pipeline ready which communicates using channels, from extraction of a zip file to storage all the info to the database.

### :athletic_shoe: How to Build and Test the Change
rebuild components/infra-proxy-service/

Only Unzip routine is working flawlessly, and rest of the function, routines needs to be updated with actual data to test and run.

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-01-31 11:05 UTC, kalroy requested changes
General feedback:
1. Add json tags for every field
2. Add a comment for every field in structs

2022-01-31 11:05 UTC, kalroy commented on components/infra-proxy-service/pipeline/phase1_migration/temp.go
> +	IsAdmin     bool
Not needed

2022-01-31 11:05 UTC, kalroy commented on components/infra-proxy-service/pipeline/phase1_migration/phase1_migration.go
> +	Users   []User
Instead of using User here we can create a minified structure:
UserAssociation: 
```
{
    Username
    IsAdmin
}
```

2022-01-31 11:05 UTC, kalroy commented on components/infra-proxy-service/pipeline/phase1_migration/temp.go
> +type User struct {
Add these fields:
AutomateUsername
Connector
IsConflicting

2022-02-04 11:22 UTC, kalroy approved these changes

2022-02-04 12:39 UTC, sonali523 approved these changes
Looks good to me

2022-02-04 12:47 UTC, YashviJain01 approved these changes

2022-02-04 17:18 UTC, merged