Pappu/stalwart 35
chef/automate pull request #6713
Opened 2022-02-18 06:15 UTC by dave-augustus

### :nut_and_bolt: Description: What code changed, and why?
Get users for backup zip, where the key_dump.json is being read and being parsed as User.
Conditions are being checked before populating result variable.
- Lint issue is also checked for Unzip
- 

### :chains: Related Resources

The ticket created for the PR can be found below
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-35

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

rebuild components/infra-proxy-service/

and upload a zip file and details must get stored in migration table.

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-02-18 08:02 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +				ActionOps: 3,
use pipeline.Insert/Pipeline.update/pipeline.SKip rather than the numbers

2022-02-18 08:02 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +			for _, sUser := range serverUser {
Here we are executing loop inside the loop. Won't it increase the time complexity of the code.

2022-02-18 08:02 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility_test.go
> +		result: pipeline.Result{Meta: pipeline.Meta{UnzipFolder: "/Users/pappuk/Downloads/backup", ServerID: "server1", MigrationID: "mig1"}},
use the testdata instead and right the test cases.

2022-02-19 20:52 UTC, kalroy requested changes

2022-02-19 20:52 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	for _, aUser := range automateUser {
This is a very inefficient way of finding and handling comparing two set of users. Should change it to a map so that a single loop can work

2022-02-19 20:52 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	for _, aUser := range automateUser {
comparing at order of n^2. Should be easily transformed to order of n

2022-02-19 20:52 UTC, kalroy commented on components/infra-proxy-service/storage/postgres/automate_infra_server_users.go
> +func (p *postgres) GetUsers(ctx context.Context, serverID string) ([]storage.User, error) {
There is already a function `GetAutomateInfraServerUsers`. Why have we added a new function here?

2022-02-19 20:52 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility_test.go
> +	require.NotNil(t, res)
Insufficient assertions. Need to check the result outcome

2022-02-19 20:59 UTC, kalroy requested changes

2022-02-19 20:59 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +func SkipUpdateUserCheck(sUser pipeline.User, aUser storage.User, checked map[string]bool) pipeline.User {
Why is this function public?

2022-02-19 20:59 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +func IfDeleted(users []pipeline.User, user string) bool {
Why is it public? Internal functions should be private

2022-02-21 04:30 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +		_, _ = mst.FailedUsersParsing(ctx, result.Meta.MigrationID, result.Meta.ServerID, err.Error(), 0, 0, 0)
Please removes these, as it will be the part of pipeline

2022-02-21 04:30 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +			_ = os.MkdirAll(fpath, os.ModePerm)
Can we check this error? as it will be a valid one

2022-02-21 09:11 UTC, sonali523 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	_ = reader.Close()
Close is called multiple times for the same reader. we can call it once

2022-02-21 09:12 UTC, sonali523 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +				parsedUsers = append(parsedUsers, sUser)
Instead of adding pivotal user to the skip, we can directly continue on the loop

2022-02-21 09:15 UTC, sonali523 commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +			_, _ = mst.FailedUnzip(ctx, result.Meta.MigrationID, result.Meta.ServerID, "cannot create a file", 0, 0, 0)
As discussed,instead of adding the database entries in utility functions we are adding it in the pipeline

2022-02-21 19:08 UTC, kalroy requested changes

2022-02-21 19:08 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +		userExists := checkUserExist(ctx, localUserClient, sUser)
Check user existence for new users. Should be inside the else block

2022-02-23 05:19 UTC, YashviJain01 approved these changes

2022-02-23 06:04 UTC, sonali523 approved these changes

2022-02-23 06:10 UTC, merged