Dave/stalwart 27
chef/automate pull request #6719
Opened 2022-02-21 03:46 UTC by dave-augustus

### :nut_and_bolt: Description: What code changed, and why?
The pipeline function is written to validate an unzip file.
The function basically checks if the unzip backup has organisations folder or not

### :chains: Related Resources
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-27

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

rebuild components/infra-proxy-service/

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-02-21 07:11 UTC, dave-augustus commented on components/infra-proxy-service/migrations/pipeline/utility_test.go
> +	require.NoError(t, err)
We are doing it already require.True(t, res.Meta.IsValid)

2022-02-21 07:14 UTC, YashviJain01 commented on components/infra-proxy-service/migrations/pipeline/utility_test.go
> +	require.NoError(t, err)
I think then require.True is only required.

2022-02-21 07:40 UTC, dave-augustus commented on components/infra-proxy-service/migrations/pipeline/utility_test.go
> +	require.NoError(t, err)
Yes

2022-02-21 11:55 UTC, YashviJain01 approved these changes

2022-02-21 18:30 UTC, kalroy requested changes

2022-02-21 18:30 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	_, err = os.Stat(unzipFolder + "/organizations")
We should be implementing it this way:
1. Find under unzip folder where the organisations folder exist. So if it is under <unzip_folder>/backup_20220221/new_backup/organisations
2. Set the location in results.Meta.UnzipFolder. Here it should be result.Meta.UnzipFolder = <unzip_folder>/backup_20220221/new_backup
3. Check key_dump.json in the same location so we expect key_dump.json under <unzip_folder>/backup_20220221/new_backup

2022-02-22 14:12 UTC, kalroy approved these changes

2022-02-22 14:36 UTC, sonali523 commented
@kalroy In this issue, should we check for members.json and admins.json?
At least empty files should be there

2022-02-22 17:03 UTC, merged