REmove special char from project names
chef/automate pull request #7023
Opened 2022-05-11 13:26 UTC by dave-augustus

Signed-off-by: Pappu Kumar <pappu.kumar@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
The Project Id doesn't support special chars. so the idea was to remove special chars from project id and name using regex before inserting them to the db

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change
- rebuild components/infra-proxy-service/
- create a lengthy server with id > 48 chars
- try uploading a backup file
- and click confirm migrations 

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-05-12 09:38 UTC, kalroy requested changes
@dave-augustus  Have a look at the UI where we are making sure we are passing the project name in the header

2022-05-12 09:38 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	// NOTE: Project name shouldn't be bigger then 48 chars, so remove all the special chars from
```suggestion
	// NOTE: Project name shouldn't be bigger then 48 chars, so remove all the special chars
```

2022-05-12 09:38 UTC, kalroy commented on components/infra-proxy-service/migrations/pipeline/utility.go
> +	serverId = validation(serverId)
Function name can be improved, something which indicates its purpose

2022-05-13 14:35 UTC, kalroy approved these changes

2022-05-16 05:11 UTC, YashviJain01 approved these changes

2022-05-16 05:38 UTC, merged