Password fix on sonarcloud
chef/automate pull request #7066
Opened 2022-05-24 12:42 UTC by Sunanda-Boorla

Signed-off-by: Sunanda-Boorla <sboorla@progress.com>

### :nut_and_bolt: Description: To Solve Security Issue in SonarCloud on Hardcoded Password. I have written a function (getPassword()) that returns a password. This password is assigned to a variable userPass. 

### :chains: https://chefio.atlassian.net/jira/software/c/projects/SHIELD/boards/365?modal=detail&selectedIssue=SHIELD-57

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-05-26 05:49 UTC, shaik80 approved these changes

2022-05-26 07:34 UTC, atultherajput commented on components/automate-deployment/pkg/usermgmt/client/client_test.go
> +		userPass := getPassword()
Why is the variable name changed from password to userPass?

2022-05-27 10:15 UTC, shaik80 requested changes

2022-05-27 10:15 UTC, shaik80 commented on components/local-user-service/users/dex/dex_test.go
> +}
add new line here

2022-05-27 10:25 UTC, Sunanda-Boorla commented on components/local-user-service/users/dex/dex_test.go
> +}
Done

2022-05-27 12:07 UTC, shivangi-singh1 approved these changes

2022-05-30 05:46 UTC, vivekshankar1 approved these changes

2022-05-30 06:11 UTC, atultherajput approved these changes
Looks good.

2022-05-30 06:15 UTC, vivekshankar1 approved these changes

2022-05-30 06:15 UTC, merged