show older scan job report
chef/automate pull request #7143
Opened 2022-06-06 09:04 UTC by shaik80

Signed-off-by: shaik80 <sh.mudassir98@gmail.com>

### :nut_and_bolt: Description: What code changed, and why?

In this PR, there is a fix to show old scan report, before this fix  it use to latest scan report because of this old scan report was shown empty
### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-06-07 06:24 UTC, shaik80 commented on components/compliance-service/reporting/relaxting/stats.go
> +	depth, err := backend.NewDepth(filters, latestOnly)
yes we can

2022-06-07 09:58 UTC, atultherajput commented on components/compliance-service/reporting/relaxting/stats.go
> +	logrus.Println(latestOnly, filters["job_id"], "scanIssue reportType")
Do we need to log this message? If yes, then can we change the level to debug?

2022-06-07 09:58 UTC, atultherajput commented on components/compliance-service/reporting/relaxting/util.go
> +	fmt.Println(filters)
Is this print statement required? If yes, then can we replace it with a log message?

2022-06-07 09:58 UTC, atultherajput commented on components/compliance-service/reporting/relaxting/util.go
> +		fmt.Println(filters, 222)
Same comment as above.

2022-06-07 12:52 UTC, atultherajput approved these changes

2022-06-08 08:27 UTC, vivekshankar1 requested changes
https://user-images.githubusercontent.com/59958706/172569478-685abfb1-4006-4c7c-a900-014ca01d1b6c.mov

Last scan job 3: data was present 
but older scan job data like profile, nodes are not visible

2022-06-08 13:46 UTC, vivekshankar1 approved these changes
Works fine, thanks

2022-06-08 14:25 UTC, vivek-yadav approved these changes

2022-06-09 05:12 UTC, merged