Sahithi/stalwart-162
chef/automate pull request #7198
Opened 2022-06-22 14:38 UTC by SahithiMy

### :nut_and_bolt: Description: What code changed, and why?
  Added a function regarding the day_latest and daily_latest flag, Based on the range this returns the day latest or daily latest.

### :chains: Related Resources
https://chefio.atlassian.net/browse/STALWART-162

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change
rebuild components/compliance-service/
chef_load_compliance_scans

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-06-22 15:45 UTC, kalroy requested changes

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			panic(err)
We cannot panic in code. The error needs to be handled

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			if len(s) == 1 && s[0] == "daily_latest" {
This complete code can be moduled out to a different function or at least a loop.

```
for search_field := range s {
      termQuery := elastic.NewTermsQuery(search_field, true)
      boolQuery = boolQuery.Must(term query)
}
```

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports_test.go
> +func TestFilterQuerychange(t *testing.T) {
Success, failure and corner cases need to tested. This is not a good way of writing unit tests.

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			logrus.Error("Range should be less than 90 days")
The error should not only be logged but also responded back to the API. We cannot continue if the diff is more than 90 days

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			logrus.Error("Start date should not be greater than end date")
Same her

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			panic(err)
Cannot panic!!!!!

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +		diff := endtime.Sub(starttime).Hours() / 24
```suggestion
		diff := int(endtime.Sub(starttime).Hours() / 24)
```

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	} else {
Unnecessary `else` block

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	endtime, err := time.Parse(layout, endTime)
Follow a single naming pattern and it has to be `camelCase`

2022-06-22 15:45 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +	layout := "2006-01-02T15:04:05Z"
No need of the layout. Should be put directly on the Parse function

2022-06-23 04:58 UTC, kalroy approved these changes

2022-06-23 07:10 UTC, dave-augustus commented on components/compliance-service/reporting/relaxting/reports_test.go
> +	s, err := filterQuerychange(filters)
give s a meaningful name.

2022-06-23 07:10 UTC, dave-augustus commented on components/compliance-service/reporting/relaxting/reports_test.go
> +	a, err := filterQuerychange(filters1)
give 'a' a meaningful name

2022-06-23 13:14 UTC, YashviJain01 approved these changes

2022-06-23 13:22 UTC, dave-augustus approved these changes

2022-06-23 14:37 UTC, kalroy requested changes

2022-06-23 14:37 UTC, kalroy commented on components/compliance-service/reporting/relaxting/reports.go
> +			return nil
If we return nil, how will the API respond back to the user with the message?

2022-06-24 09:41 UTC, dave-augustus approved these changes

2022-06-27 05:21 UTC, merged