changes for previous day latest
chef/automate pull request #7211
Opened 2022-06-28 11:07 UTC by SahithiMy

Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-06-29 06:45 UTC, kalroy requested changes
The coverage is again a concern and we have a code smell too. Please keep a note of the file to be included in the unit test coverage.

2022-06-29 06:45 UTC, kalroy commented on components/compliance-service/ingest/ingestic/ingestic.go
> +func (backend *ESClient) SetDayLatestToFalseForControlIndex(ctx context.Context, controlId string, profileId string, mapping mappings.Mapping, index string, node_uuid string) error {
We follow camelcase. Rename this parameter `node_uuid` to `nodeUuid`

2022-06-29 06:45 UTC, kalroy commented on components/compliance-service/ingest/ingestic/ingestic.go
> +	script := elastic.NewScript("def targets = ctx._source.nodes.findAll(node -> node.node_uuid == params.node_uuid); for(node in targets) { if(node.day_latest==true) {node.day_latest = false}} if (ctx.
This line needs formatting. It is unreadable

2022-06-29 12:31 UTC, dave-augustus approved these changes

2022-06-29 15:32 UTC, Dmaddu requested changes

2022-06-29 15:32 UTC, Dmaddu commented on components/compliance-service/ingest/ingestic/ingestic.go
> +		logrus.Errorf("Cannot get indexes: %+v", err)
we need to do error handling properly, here we are just printing the error. In this case, we need to send the error to the caller.

2022-06-29 15:32 UTC, Dmaddu commented on components/compliance-service/ingest/ingestic/ingestic.go
> +	oneDayAgo := time.Now().Add(-24 * time.Hour)
variable naming is not correct, please rename, if not simply pass the values to relaxting.IndexDates method and add the comments

2022-06-29 15:32 UTC, Dmaddu commented on components/compliance-service/ingest/ingestic/ingestic.go
> +func (backend *ESClient) SetDayLatestToFalseForControlIndex(ctx context.Context, controlId string, profileId string, mapping mappings.Mapping, index string, nodeId string) error {
please add a description for the method.

2022-07-04 15:24 UTC, kalroy approved these changes

2022-07-04 15:24 UTC, merged