Dave/stalwart 186
chef/automate pull request #7226
Opened 2022-07-04 12:05 UTC by dave-augustus

### :nut_and_bolt: Description: What code changed, and why?
Add/Modify Integration test to test the ingestion pipeline for new control index

### :chains: Related Resources

### :+1: Definition of Done
- The pipeline should be running on every changes to a PR
- The pipeline should be green on execution
- The test should include scenarios to check that we have the current number of controls which should match all the controls for all the reports in DB
- The test should include that the structure should be maintained 
- The tests should include the validation of data pushed into the new index
### :athletic_shoe: How to Build and Test the Change
run the following command in hab terminal
`compliance_integration`
or
we can check buildkite pipeline
### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-07-05 04:31 UTC, kalroy requested changes

2022-07-05 04:31 UTC, kalroy commented on components/compliance-service/ingest/pipeline/processor/control_worker.go
> +	logrus.Infof("Parsed results got results")
```suggestion
	logrus.Debugf("Parsed results got results")
```

2022-07-05 04:31 UTC, kalroy commented on components/compliance-service/integration_test/compliance_reporting_test.go
> +	require.NotEqual(t, 0, searchResult.TotalHits())
We need to validate the structure of the index

2022-07-05 04:31 UTC, kalroy commented on components/compliance-service/ingest/ingestic/ingestic.go
> -			continue
why have we removed this code?

2022-07-05 15:39 UTC, YashviJain01 approved these changes

2022-07-06 06:04 UTC, kalroy approved these changes

2022-07-06 06:04 UTC, merged