Added Migration from Automate to Automate HA using S3
chef/automate pull request #7242
Opened 2022-07-11 10:07 UTC by Sathvikreddy14

Signed-off-by: Sathvikreddy14 <creddy@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
In this PR, I have added Process for Migration of Automate to Automate HA using S3 Bucket

### :chains: Related Resources
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-246

### :+1: Definition of Done
It has been tested 

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-07-12 05:40 UTC, jayvikramsharma1 commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +
### Title for backup can be added here

2022-07-12 10:07 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +Follow [Backup COnfiguration for S3 Backup](https://docs.chef.io/automate/ha_backup_restore_prerequisites/#pre-backup-configuration-for-s3-backup)
```suggestion
Follow [Backup Configuration for S3 Backup](https://docs.chef.io/automate/ha_backup_restore_prerequisites/#pre-backup-configuration-for-s3-backup)
```

2022-07-12 12:10 UTC, vivek-yadav approved these changes

2022-07-12 12:23 UTC, ArvinthC3000 requested changes

2022-07-13 05:32 UTC, punitmundra approved these changes

2022-07-13 05:33 UTC, ArvinthC3000 approved these changes

2022-07-13 05:36 UTC, merged