Control Summary From New Control Index
chef/automate pull request #7255
Opened 2022-07-19 09:21 UTC by YashviJain01

Signed-off-by: Yashvi Jain <yashvi.jain@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

The control summary api which gives the counts of failed, Passed, skipped and waived controls is now getting data from new control index. Which will also take care of the filtering process

### :chains: Related Resources

https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-170

### :+1: Definition of Done

Control summary is getting the correct number of counts over a date range now.

### :athletic_shoe: How to Build and Test the Change

Upload some data into compliance.
Use below curl command

```
curl --location --request POST 'https://a2-dev.test/api/v0/compliance/reporting/stats/summary' \
--header 'api-token: {get_admin_token}' \
--header 'Content-Type: application/json' \
--data-raw '{"type":"controls"}'
```

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-07-20 15:58 UTC, Dmaddu requested changes

2022-07-20 15:58 UTC, Dmaddu commented on components/compliance-service/ingest/pipeline/processor/parse_struct.go
> +			nodes := make([]relaxting.Node, 0)
with this modification, test cases are failing. please fix them

2022-07-21 09:33 UTC, Dmaddu approved these changes

2022-07-21 10:35 UTC, kalroy approved these changes

2022-07-21 10:35 UTC, merged