Vivek/stalwart 181
chef/automate pull request #7304
Opened 2022-08-05 10:49 UTC by VivekSharma2607

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change
rebuild command = components/compilance_serivce 
rebuild components/automate-gateway
curl for testing 
`curl --location --request POST 'https://a2-dev.test/api/v0/compliance/reporting/assets/count' \
--header 'api-token: GD2cbnOQTLICLPMhs7OiFZZfGtA=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "filters": [
        {
            "type": "start_time",
            "values": [
                "2022-05-05T00:00:00Z"
            ]
        },
        {
            "type": "end_time",
            "values": [
                "2022-08-05T00:00:00Z"
            ]
        }
    ]
}'`
### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-08-05 11:15 UTC, dave-augustus requested changes

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/reporting/relaxting/assets.go
> +	// Todo hardcoding the value for Reachable assets
Remove the TODO line as it causes code smells

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/reporting/relaxting/assets.go
> +		logrus.Errorf("The error while getting the unreported Assests %v", err)
```suggestion
		logrus.Errorf("The error while getting the collected assets: %v", err)
```

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/api/reporting/server/server.go
> +	} else {
As previous conditions are returning, this else isn't required,  remove the else condition and put the block statemnt below line 925

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/api/reporting/server/server.go
> +	if len(formatttedFilters["start_time"]) <= 0 || len(formatttedFilters["end_time"]) <= 0 {
log and return

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/api/reporting/server/server.go
> +		return nil , &errorutils.InvalidError{}
log and return

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/api/reporting/server/server.go
> +				return nil , errorutils.FormatErrorMsg(err , "")
log and return

2022-08-05 11:15 UTC, dave-augustus commented on components/compliance-service/api/reporting/server/server.go
> +				return nil , errorutils.FormatErrorMsg(err , "")
log and return

2022-08-05 12:08 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +		start_date := formatttedFilters["start_time"]
validate this in another function. Rename the variables as well. Create a function which validated start time and end time. Take the layout as ttime.RFC3339.

2022-08-05 12:10 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +			count.Collected = assets.Collected
Why are we taking two variables, can we do this in one?

2022-08-08 11:41 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +func Validate(startTime string , endTime string) (bool , error) {
rename the function to what?

2022-08-08 11:41 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +	if reflect.DeepEqual(formattedFilters["start_time"] , formattedFilters["end_time"]) {
add this logic in the function itself.

2022-08-08 11:41 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +	timeRange, err := Validate(formattedFilters["start_time"][0] , formattedFilters["end_time"][0])
this logic as well.

2022-08-08 11:41 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +	if len(formattedFilters["start_time"]) <= 0 || len(formattedFilters["end_time"]) <=0 {
Add this logic in the function in validate function.

2022-08-09 06:49 UTC, daveaugustus approved these changes

2022-08-09 14:15 UTC, merged