Dave/stalwart 189
chef/automate pull request #7327
Opened 2022-08-17 11:43 UTC by daveaugustus

### :nut_and_bolt: Description: What code changed, and why?

As an Automate user, I need to store the unreachable configuration in data-lifecycle settings in compliance db

### :chains: Related Resources

### :+1: Definition of Done
- API should throw error if start date > end date
- API should throw error if end date - start date > 90 days
- All Exceptions are Handled Properly
- Ensure logs have no unnecessary data.
- Test coverage for the new feature is done to at least 70%
- Swagger Documentation updated
- Smoke Test done.
- Ensure Build and Integration Pipelines are Green.
- PR has 2 approvers.
- All Code Review Comments are Resolved.
- README doc should be updated, if needed.
### :athletic_shoe: How to Build and Test the Change
`rebuild components/compliance-service/`
### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-08-17 17:52 UTC, kalroy requested changes
Let's add unit tests for the newly added code.

2022-08-17 17:52 UTC, kalroy commented on components/compliance-service/api/reporting/server/server.go
> +func New(es *relaxting.ES2Backend, rm reportmanager.ReportManagerServiceClient, LRCOpenSearchRequest int, db *pgdb.DB) *Server {
```suggestion
func New(es *relaxting.ES2Backend, rm reportmanager.ReportManagerServiceClient, lcrOpenSearchRequest int, db *pgdb.DB) *Server {
```

2022-08-17 17:52 UTC, kalroy commented on components/compliance-service/api/reporting/server/server.go
> +		lcr_open_search_requests: LRCOpenSearchRequest,
```suggestion
		lcr_open_search_requests: lcrOpenSearchRequest,
```

2022-08-17 17:52 UTC, kalroy commented on api/external/compliance/reporting/reporting.proto
> +    string policy_name = 1;
We should not give user option to pass the policy name. He can pass an arbitrary name in the policy name which we won't be able to use.

2022-08-17 17:52 UTC, kalroy commented on api/interservice/compliance/reporting/reporting.proto
> +    string policy_name = 1;
We can utilise it here so that we can call the same service for every policy updates

2022-08-17 17:52 UTC, kalroy commented on api/external/compliance/reporting/reporting.proto
> +    string policy_name = 1;
We should different APIs for every config or we need to assert the policies being passed.

2022-08-18 05:31 UTC, Dmaddu requested changes
Some sonar cloud failures at 
components/report-manager-service/worker/worker_test.go#L787

you might need to make some changes on components/compliance-service/integration_lcr_test as well

2022-08-18 06:43 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +	err := relaxting.ValidateTimeRangeForFilters(formattedFilters["start_time"][0], endTime)
why are we changing this function?

2022-08-18 07:38 UTC, YashviJain01 commented on components/compliance-service/dao/pgdb/config.go
> +	row := db.QueryRow("SELECT policy_name, older_than_days FROM compliance_lifecycle;")
From where are we getting this policy name?

2022-08-18 07:38 UTC, YashviJain01 commented on components/compliance-service/dao/pgdb/migration/sql/42_create_data_lifecycle.up.sql
> +  older_than_days INTEGER NOT NULL
Do we want to store the updated time as well? Rather than older_than_days , can we rename to policy_value?

2022-08-18 07:38 UTC, YashviJain01 commented on components/compliance-service/dao/pgdb/migration/sql/42_create_data_lifecycle.up.sql
> +INSERT INTO compliance_lifecycle (policy_name, older_than_days) VALUES ('unreachable-assets', 60);
use "_" instead of "-"

2022-08-18 09:11 UTC, YashviJain01 commented on api/external/compliance/reporting/reporting.proto
> +message ComplianceConfigRequest{
Please add come comments to update the swagger documentation. @SahithiMy  @daveaugustus

2022-08-18 09:11 UTC, YashviJain01 commented on components/compliance-service/api/reporting/server/server.go
> +		logrus.Errorf("error whoile getting the conf: %+v", err)
please correct this type mistake. @SahithiMy

2022-08-18 09:11 UTC, YashviJain01 commented on components/compliance-service/dao/pgdb/config.go
> +		return errors.New("didn't update any row")
Can we have proper error.

2022-08-18 11:00 UTC, daveaugustus commented
> Some sonar cloud failures at components/report-manager-service/worker/worker_test.go#L787
> 
> you might need to make some changes on components/compliance-service/integration_lcr_test as well

@Dmaddu  Fixed it.

2022-08-18 11:43 UTC, YashviJain01 commented on api/external/compliance/reporting/reporting.proto
> +    string policy_name = 1;
Can you please add comments for properties as well @SahithiMy

2022-08-18 11:51 UTC, YashviJain01 commented on api/external/compliance/reporting/reporting.proto
> +	rpc SetAssetConfig(ComplianceConfigRequest) returns (ComplianceConfigResponse) {
Please add a comment what does this API do? What the API contract?

2022-08-18 13:07 UTC, YashviJain01 commented on api/external/compliance/reporting/reporting.proto
> +    int32 no_of_days = 1;
We can change this to policy_value, as a user prospective no_of_days doesn't sound valid.

2022-08-18 13:07 UTC, YashviJain01 approved these changes

2022-08-18 13:52 UTC, kalroy approved these changes

2022-08-18 14:16 UTC, merged