Adding resolver documentation
chef/automate pull request #7422
Opened 2022-09-20 07:33 UTC by YashviJain01

Signed-off-by: Yashvi Jain <yashvi.jain@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
Adding resolver documentation in managed services as well

### :chains: Related Resources

https://chefio.atlassian.net/browse/STALWART-218

### :+1: Definition of Done

Added documentation

### :athletic_shoe: How to Build and Test the Change

See the preview changes

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-09-22 07:06 UTC, YashviJain01 commented
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/91940132/191680485-1c2a71f0-5f01-4843-8c4b-8b98fed751b2.png">

Resolver document in managed services for postgress

2022-09-22 07:13 UTC, YashviJain01 commented
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/91940132/191682076-bd161640-7af4-4c5a-9dc0-bf04899da933.png">

Resolver section in managed services for opensearch

2022-09-23 05:58 UTC, punitmundra commented on components/docs-chef-io/content/automate/managed_services.md
> +1. Run `chef-automate config show config.toml`.
chef-automate config show  > config.toml

2022-09-23 05:58 UTC, punitmundra requested changes

2022-09-23 05:58 UTC, punitmundra commented on components/docs-chef-io/content/automate/managed_services.md
> +1. Run `chef-automate config show config.toml`.
chef-automate config show > config.toml

2022-09-23 06:07 UTC, YashviJain01 commented
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/91940132/191900892-8b59ff1d-2b53-4928-b173-2cd4ec20e185.png">

Postgres resolver

2022-09-23 06:08 UTC, YashviJain01 commented
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/91940132/191900954-ede9e2a9-cb01-4232-bbb1-799f5633cd2e.png"> 

Opensearch resolver

2022-09-23 06:11 UTC, punitmundra approved these changes

2022-09-27 08:43 UTC, dishanktiwari2501 approved these changes

2022-09-27 09:46 UTC, YashviJain01 commented
> As per the ticket, the changes should be done as part of https://docs.chef.io/automate/troubleshooting/ as well. But I don't see the changes with the preview link. Please update the JIRA ticket with updated acceptance criteria if these are not required.


Removed from the story, troubleshooting was not required as we couldn't find anything there.

2022-09-27 09:55 UTC, merged