Adding configuration for redirecting journalctl logs to a file
chef/automate pull request #7508
Opened 2022-10-28 09:53 UTC by YashviJain01

### :nut_and_bolt: Description: What code changed, and why?

After adding the below configuration the logs will be redirecting to /var/log/automate.log

[global.v1.log]
    redirectSysLog = true

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

rebuild components/automate-deployment/
rebuild components/automate-cli/

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-02 17:21 UTC, Dmaddu commented
@YashviJain01  @daveaugustus  Please record a demo video and attach it to this PR.

2022-11-03 04:47 UTC, YashviJain01 commented
https://user-images.githubusercontent.com/91940132/199649469-87579352-955f-49ef-979c-cb6f05bd0394.mov

2022-11-04 10:32 UTC, YashviJain01 commented
https://user-images.githubusercontent.com/91940132/199951865-387c6f8c-d4f5-4171-aaa1-5410c68fd247.mov

2022-11-07 05:24 UTC, kalroy approved these changes

2022-11-07 07:42 UTC, Dmaddu requested changes

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/helpers.go
> +	return fmt.Sprintf("%sautomate.log", path)
there can be a possibility that the user doesn't provide the `/` at the end. So please make sure to support that as well.

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/automate_config.go
> +			return status.Error(codes.Internal, "Failed to create configuration into syslog")
here we are swallowing the actual error. If we would like to display an error message similar to this, then write the actual error message at least in the logs.

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/automate_config.go
> +			return status.Error(codes.Internal, "Failed to restart syslog service")
same thing here as well.

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/automate_config.go
> +			return status.Error(codes.Internal, "Failed to remove configuration into syslog")
same thing here as well.

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/automate_config.go
> +			return status.Error(codes.Internal, "Failed to restart syslog service while removing config file for syslog")
same thing here as well.

2022-11-07 07:42 UTC, Dmaddu commented on components/automate-deployment/pkg/server/automate_config.go
> +func restartSyslogService() error {
please add a description to all the new methods, at least one or two liners describe the actual operation we are doing over that method.

2022-11-07 07:56 UTC, Dmaddu commented on components/automate-deployment/pkg/server/helpers.go
> +func LogRotateConf(path string, params ...string) string {
what if we pass empty params? something like 
LogRotateConf(" some path", "copytruncate", "")

2022-11-07 09:25 UTC, Dmaddu approved these changes

2022-11-07 10:02 UTC, merged