Documentation for On Prem with AWS Managed Services
chef/automate pull request #7516
Opened 2022-10-31 09:21 UTC by Sathvikreddy14

Signed-off-by: Sathvikreddy14 <creddy@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-03 11:47 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +### Minimum changes to be made for On Premise Deployment
```suggestion
### Minimum changes to be made for On-Premise Deployment
```

2022-11-03 11:47 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +## On Premise Setup with AWS Managed Services.
```suggestion
## On-Premise Setup with AWS Managed Services.
```

2022-11-03 11:47 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- Follow the Prerequisites for On Premise deployment. Click [here](https://docs.chef.io/automate/ha_onprim_deployment_procedure/#prerequisites).
Chang `On Premise` to 'On-Premise' wherever applicable

2022-11-03 13:19 UTC, punitmundra requested changes

2022-11-03 13:19 UTC, punitmundra commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- Get AWS credetials (`aws_access_key_id` and `aws_secret_access_key`) which have privileges like: `AmazonS3FullAccess`, `AdministratorAccess`, `AmazonAPIGatewayAdministrator`. Click [here](/automate
why this(AmazonAPIGatewayAdministrator) is required ?

2022-11-03 13:19 UTC, punitmundra commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- You can exclude the creation of instances for OpenSearch and Postgresql as you will be using AWS OpenSearch and AWS RDS Postgresql.
reframe the sentence. This deployment excludes the installation for PG and OS as we are using the AWS Managed services.

2022-11-07 10:02 UTC, jayvikramsharma1 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Set `instance_url`, `superuser_username`, `superuser_password`, `dbuser_username`, `dbuser_password` of your Self Managed RDS.
for your Self Managed RDS.

2022-11-07 10:02 UTC, jayvikramsharma1 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Set `opensearch_domain_name`, `opensearch_domain_url`, `opensearch_username`, `opensearch_user_password` of your Self Managed OpenSearch.
for your Self Managed OpenSearch.

2022-11-07 10:16 UTC, Sathvikreddy14 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Set `opensearch_domain_url` as the URL without Port No. For example: `"vpc-automate-ha-cbyqy5q.eu-north-1.es.amazonaws.com"`.
In case of AWS Managed Services, port no is not required

2022-11-07 11:15 UTC, jayvikramsharma1 approved these changes

2022-11-07 13:41 UTC, punitmundra approved these changes

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- Create the Virtual Private Cloud (VPC) in AWS before starting or using default. Click [here](/automate/ha_vpc_setup/) to know more about VPC and CIDR creation.
Create the Virtual Private Cloud (VPC) in AWS or use the default one

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- Get AWS credetials (`aws_access_key_id` and `aws_secret_access_key`) which have privileges like: `AmazonS3FullAccess`, `AdministratorAccess`. Click [here](/automate/ha_iam_user/) to know more on ho
```suggestion
- Get AWS credentials (`aws_access_key_id` and `aws_secret_access_key`) which have privileges that includes: `AmazonS3FullAccess`, and `AdministratorAccess`. Click [here](/automate/ha_iam_user/) to know more about how to create IAM Users.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Provide instance count as `0` for [opensearch.config] and [postgresql.config] and leave the values of opensearch_private_ips and postgresql_private_ips as empty.
```suggestion
    - Provide instance count as `0` for both [opensearch.config] and [postgresql.config] and leave the values of opensearch_private_ips and postgresql_private_ips empty array.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Set `type` as `aws`, As these deployment steps are for Managed Services AWS Deployment. The default value is blank, which should be changed.
```suggestion
    - Set `type` as `aws`, as these deployment steps are for Managed Services AWS Deployment. The default value is blank.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +- This deployment excludes the installation for Postgresql and OpenSearch as we are using the Self Managed services.
Make it a note

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Provide instance count as `0` for [opensearch.config] and [postgresql.config] and leave the values of opensearch_private_ips and postgresql_private_ips as empty.
```suggestion
    - Provide instance count as `0` for both [opensearch.config] and [postgresql.config] and leave the values of opensearch_private_ips and postgresql_private_ips empty array.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
> +    - Set `type` as `self-managed`, As these deployment steps are for Managed Services AWS Deployment. The default value is blank, which should be changed.
```suggestion
    - Set `type` as `self-managed`, As these deployment steps are for Managed Services AWS Deployment. The default value is blank.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
>  - Add the `Ip address` for the respetive node at the end, as explained in the example.
```suggestion
- Add the IP address for the respective node at the end, as explained in the example.
```

2022-11-07 13:42 UTC, ArvinthC3000 commented on components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
>  - Make sure that all the necesssary port and fire wall setting are align in the new node.
```suggestion
- Make sure that all the necessary ports and firewall settings are aligned in the new node.
```

2022-11-08 12:45 UTC, dishanktiwari2501 approved these changes

2022-11-10 08:58 UTC, merged