Jay/madrox 375
chef/automate pull request #7523
Opened 2022-11-03 05:17 UTC by jayvikramsharma1

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-03 05:29 UTC, vivek-yadav commented on components/automate-cli/cmd/chef-automate/backup.go
> +	if NewBackupFromBashtion().isBastionHost() {
Spelling "Bastion"

2022-11-03 17:59 UTC, ArvinthC3000 approved these changes

2022-11-04 06:03 UTC, punitmundra commented on components/automate-cli/cmd/chef-automate/backup.go
> +	writer.Printf("triggered backup commands in Automate remote machine from bashtion host response \n %s \n", res)
can we add the ip of the automate node

2022-11-14 10:12 UTC, punitmundra requested changes
Do the rebase
resolve the conflicts 
Add the video

2022-11-16 13:15 UTC, punitmundra approved these changes

2022-11-16 16:09 UTC, merged