chef-automate gather-logs for faulty nodes
chef/automate pull request #7525
Opened 2022-11-08 12:39 UTC by SahithiMy

Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-14 04:58 UTC, Dmaddu commented
@SahithiMy I didn't see any sync between the PR and the corresponding ticket. Does the requirement get modified?
Lets have a discussion on this

2022-11-14 04:59 UTC, Dmaddu requested changes
Let's have a discussion regarding the changes you have made.

2022-11-14 09:44 UTC, Dmaddu approved these changes

2022-11-14 12:20 UTC, punitmundra approved these changes

2022-11-15 05:16 UTC, YashviJain01 approved these changes

2022-11-15 06:17 UTC, merged