cert rotate cmd for OS
chef/automate pull request #7526
Opened 2022-11-09 07:21 UTC by Sahiba3108

Signed-off-by: Sahiba3108 <sgoyal@progress.com>
SanjuPal01 <sanju.sanju@progress.com>
### :nut_and_bolt: Description: What code changed, and why?
Added the cert rotate command for HA service. Now user has to pass the certificate paths to cert-rotate cmd and it will rotate the certificates of all opensearch nodes.

### :chains: Related Resources
https://chefio.atlassian.net/browse/KINETICS-231
### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change
Add this package in your manifest while deploying HA:
sahiba3108/automate-ha-deployment/0.1.0/20221028084038

Install this cli in your bastion host:
sahiba3108/automate-cli/0.1.0/20221109065332

Run the below command in bastion:
`chef-automate cert-rotate --public-cert node1.pem --private-cert node1-key.pem --root-ca root-ca.pem --admin-cert admin.pem --admin-key admin-key.pem --os`
(You can also use --opensearch flag instead of os)
This will rotate the public, private, root, admin cert and admin key of all os nodes.
### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable
<img width="1662" alt="Screenshot 2022-11-09 at 12 39 39 PM" src="https://user-images.githubusercontent.com/108404805/200764363-7fab89f2-13dc-4a92-995b-348873832200.png">
<img width="1230" alt="Screenshot 2022-11-09 at 12 32 03 PM" src="https://user-images.githubusercontent.com/108404805/200764475-b8f09345-cf56-469b-ab44-3c769ece015b.png">
<img width="1035" alt="Screenshot 2022-11-09 at 12 31 05 PM" src="https://user-images.githubusercontent.com/108404805/200764463-920002c1-8c39-4fe5-80d7-7e9d706c6a43.png">
<img width="1024" alt="Screenshot 2022-11-09 at 12 31 25 PM" src="https://user-images.githubusercontent.com/108404805/200764472-65e7ad25-b4d5-436f-89b2-b039e74492da.png">
<img width="740" alt="Screenshot 2022-11-09 at 12 40 34 PM" src="https://user-images.githubusercontent.com/108404805/200764500-d6d497c2-a10e-43f6-a2d3-679ca8b99662.png">

2022-11-09 07:47 UTC, punitmundra requested changes
please modularise the code  instead of writing the single function.

2022-11-14 06:08 UTC, Dmaddu approved these changes

2022-11-14 06:15 UTC, punitmundra approved these changes

2022-11-14 06:35 UTC, merged

2022-11-14 06:35 UTC, SanjuPal01 approved these changes