Just a draft PR
chef/automate pull request #7554
Opened 2022-11-21 15:54 UTC by daveaugustus

Signed-off-by: Pappu Kumar <pappu.kumar@progress.com>

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-24 13:56 UTC, kalroy requested changes
Please add the config:
`oc_bifrost['extended_perf_log']`

2022-11-24 13:56 UTC, kalroy commented on api/config/bifrost/config_request.go
> -	c.V1.Sys.Sql.PoolQueueMax = w.Int32(50)
Let's not change it

2022-11-24 13:56 UTC, kalroy commented on api/config/bifrost/config_request.proto
> +		message System {
unnecessary change

2022-11-25 06:46 UTC, kalroy requested changes

2022-11-25 06:46 UTC, kalroy commented on components/automate-cs-oc-bifrost/habitat/config/sys.config
> +                       {perf_log, {{cfg.log.extended_perf_log}}},
We do not need to add this config.
Modify this line 107:
`{enable_extended_perf_log, true},` to `{enable_extended_perf_log, {{cfg.log.extended_perf_log}}},`

2022-11-25 07:45 UTC, dave-augustus commented
Working fine on automate standalone
![Screenshot 2022-11-25 at 1 14 23 PM](https://user-images.githubusercontent.com/36985548/203927744-ddb71558-fc1b-4510-80ee-efda515e8047.png)

2022-11-25 11:12 UTC, kalroy approved these changes

2022-11-25 11:33 UTC, merged