Dave/stalwart 262
chef/automate pull request #7567
Opened 2022-11-23 18:42 UTC by dave-augustus

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2022-11-24 13:39 UTC, kalroy requested changes
The changes in sys.config are not correct. Needs to be fixed.

2022-11-24 13:39 UTC, kalroy commented on components/automate-cs-oc-erchef/habitat/config/sys.config
> +        {authz_cleanup_batch_size, {{cfg.authz.cleanup_batch_size}}},
We do not need to add a new config. Add the config to L158. 
Modify 
`{cleanup_batch_size, 0}` to `{cleanup_batch_size, {{cfg.authz.cleanup_batch_size}}}`

2022-11-24 13:39 UTC, kalroy commented on components/automate-cs-oc-erchef/habitat/config/sys.config
> +        {s3_url_ttl, "{{cfg.api.s3_url_ttl}}"},
We should not add new config. Change in L209
`{s3_url_ttl, 28800},` to `{s3_url_ttl, {{cfg.api.s3_url_ttl}}},`

2022-11-24 13:39 UTC, kalroy commented on components/automate-cs-oc-erchef/habitat/config/sys.config
> +    {i_browse, [
Should not add these configs. 
Change this:
`    {ibrowse, [
        {default_max_sessions, 256},
        {default_max_pipeline_size, 1}
    ]},`
    to 
   ```    
    {ibrowse, [
        {default_max_sessions, {{cfg.iBrowse.ibrowse_max_pipeline_size}}},
        {default_max_pipeline_size, {{cfg.iBrowse.ibrowse_max_sessions}}}
    ]}, 
```

2022-11-25 11:23 UTC, dave-augustus commented
Test on automate standalone the result looks fine

```
{cleanup_batch_size, 9}

{s3_url_ttl, 500},

 {ibrowse, [
        {default_max_pipeline_size, 30},
        {default_max_sessions, 300}
    ]},
```

2022-11-27 11:27 UTC, Dmaddu requested changes
@dave-augustus  Please upload the demo video as well.

2022-11-27 11:27 UTC, Dmaddu commented on api/config/bifrost/config_request.go
>  	c.V1.Sys.Sql.PoolQueueTimeout = w.Int32(2000)
plz remove the untouched files.

2022-11-27 11:27 UTC, Dmaddu commented on api/config/bifrost/config_request.proto
plz remove the untouched files

2022-11-28 13:16 UTC, daveaugustus commented
Automate HA

![Screenshot 2022-11-28 at 6 45 30 PM](https://user-images.githubusercontent.com/36985548/204287007-bb6c03b7-0a84-418d-8733-d328bf083a2a.png)

2022-11-28 15:47 UTC, kalroy approved these changes

2022-11-29 08:17 UTC, daveaugustus commented
https://user-images.githubusercontent.com/36985548/204475511-bc785b93-4786-4150-9cea-98dd83d3e932.mov

2022-11-29 14:15 UTC, merged