sahithi/STALWART-305-new
chef/automate pull request #7657
Opened 2023-01-09 08:01 UTC by SahithiMy

Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
Modified the error message for the nodes delete for opensearch nodes, postgress nodes, chefserver nodes and automate nodes in automate HA on onprem deployment.

### :chains: Related Resources
https://chefio.atlassian.net/browse/STALWART-305
### :+1: Definition of Done
Error message is modified for deleting nodes when nodes are less than minimum count.
### :athletic_shoe: How to Build and Test the Change
```rebuild components/automate-cli/```
```hab pkg install sahithimy/automate-cli/0.1.0/20230109071130 -bf```
### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

https://user-images.githubusercontent.com/98326242/211260297-908bd51d-e88f-4e98-ac53-b267738e3c5a.mov

2023-01-09 08:41 UTC, YashviJain01 commented on components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go
> +			errorList.PushBackList(checkIfPresentInPrivateIPList(dni.config.ExistingInfra.Config.AutomatePrivateIps, dni.automateIpList, "Automate"))
Do we need  else statement? if it will not go in if loop it will be in else.

2023-01-09 09:59 UTC, YashviJain01 approved these changes

2023-01-09 10:04 UTC, daveaugustus approved these changes

2023-01-09 20:07 UTC, Dmaddu requested changes

2023-01-10 13:44 UTC, Dmaddu approved these changes

2023-01-10 15:21 UTC, merged