fixed the error log issue
chef/automate pull request #7705
Opened 2023-02-06 05:04 UTC by GhanavishmathiMacharla

Signed-off-by: Ghanavishmathi Macharla <gmacharl@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
Fixed the issue of Node error log data in the Automate UI.
Minor change in resource-item component .html and .ts file to view the node error log data properly.

### :chains: Related Resources
https://chefio.atlassian.net/browse/KINETICS-254

### :+1: Definition of Done
- Code changes in resource-item component
- After changes verified the UI

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-02-06 07:16 UTC, arunjn-progress approved these changes

2023-02-06 08:22 UTC, vinay033 approved these changes

2023-02-15 09:26 UTC, arunjn-progress requested changes
Need to discuss this change. ResourceId seems to be imperative for the modal window to get details.

2023-02-16 06:27 UTC, arunjn-progress approved these changes

2023-02-16 10:36 UTC, merged