Added FAQs
chef/automate pull request #7708
Opened 2023-02-07 09:02 UTC by daveaugustus

Signed-off-by: Pappu Kumar <pappu.kumar@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
As an Automate user, I want to refer to the public document to understand all the different frequently asked questions related to centralised logging.

### :chains: Related Resources

### :+1: Definition of Done
- Add FAQs into the centralised log page.
### :athletic_shoe: How to Build and Test the Change
- Check the preview link
### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-02-14 09:12 UTC, daveaugustus commented
@kalroy  I have updated the formatting:

Referred: https://github.com/chef/automate/blob/main/components/docs-chef-io/content/automate/ha_faqs.md

2023-02-15 10:25 UTC, dishanktiwari2501 approved these changes
Reviewed and Fixed!

2023-02-20 16:16 UTC, kalroy requested changes

2023-02-20 16:16 UTC, kalroy commented on components/docs-chef-io/content/automate/centralizing_log.md
> +### Is the setting of `redirect_log_file_path` directory where the log files will be stored or the full path of the actual log file?
This does not look like a FAQ to me. This can be resolved by being more explicit in our document

2023-02-20 16:16 UTC, kalroy commented on components/docs-chef-io/content/automate/centralizing_log.md
> +- Run multiple commands, e.g.:
We should include all the steps with more details. 
- Mount an NFS or network-attached storage to all the nodes. Choose a log location
- command to patch Automate nodes with the same log location
- command to patch Server nodes with the same log location
- command to patch PG nodes with the same log location
- command to patch OS nodes with the same log location

2023-02-21 11:03 UTC, daveaugustus commented on components/docs-chef-io/content/automate/centralizing_log.md
> +Create the centralizing log file, i.e., **automate.log** in the `redirect_log_file_path` directory.
@dishanktiwari2501 Please change the line as 
```suggestion
NOTE: `redirect_log_file_path`  is a directory where automate.log gets created.
```

@kalroy  what do you say?

2023-02-21 15:34 UTC, merged