Chef Automate HA Pre-Requisites
chef/automate pull request #7735
Opened 2023-02-22 13:19 UTC by dishanktiwari2501

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-02-24 16:05 UTC, IanMadd commented on components/docs-chef-io/content/automate/chef-automate-ha-prerequisites.md
> +## On-Premise Deployment Pre-Requisite
It's "on-premises", not "on-premise". There's no such thing as "on-premise"

2023-03-06 18:03 UTC, Dmaddu commented on components/docs-chef-io/content/automate/chef-automate-ha-prerequisites.md
> +Before installing Chef automate HA on On-premise deployment, ensure you have taken a quick tour of this pre-requisite page.
`Before installing Chef automate HA on On-premise deployment` can you rewrite this sentence plz

2023-03-06 18:04 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-deployment-prerequisites.md
> +Before installing Chef automate HA on AWS deployment, ensure you have taken a quick tour of this pre-requisite page.
`Before installing Chef automate HA on AWS deployment` - can you rewrite this sentence?

2023-03-06 18:06 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-deployment-prerequisites.md
> +LoadBalancers in AWS deployment are set up according to [Chef Automate HA Architecture](/automate/ha/).
LoadBalancers will be provisioned automatically, customer does not need to create manually in this kind of deployment

2023-03-06 18:09 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-deployment-prerequisites.md
> +- Preferred key type will be ed25519=
please remove the `=` at the end

2023-03-06 18:10 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-deployment-prerequisites.md
> +- DNS is configured to redirect `chefautomate.example.com` to the Primary Load Balancer.
let's discuss these.

2023-03-06 18:19 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-managed-services-deployment-prerequisites.md
> +Before installing Chef automate HA on AWS managed services deployment, ensure you have taken a quick tour of this pre-requisite page.
please rewrite this stmt

2023-03-06 18:20 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-managed-services-deployment-prerequisites.md
> +LoadBalancers in aws managed services deployment are set up according to [Chef Automate HA Architecture](/automate/ha/).
LoadBalancers will be provisioned automatically in this mode of deployment

2023-03-06 18:21 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-managed-services-deployment-prerequisites.md
> +- Please refer to the [table](/automate/chef-automate-ha-prerequisites/#migration/) to identify the correct OpenSearch version to be installed.
Now this stmt is not needed

2023-03-06 18:24 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha-aws-managed-services-deployment-prerequisites.md
> +- Setup AWS OpenSearch with the identified version in the same VPC where we have the basion and automate ha node going to be created. Click [here](https://docs.aws.amazon.com/opensearch-service/lates
Mention the AWS OpenSearch version as 1.3

2023-03-14 09:42 UTC, vivekshankar1 commented on components/docs-chef-io/content/automate/ha-aws-deployment-prerequisites.md
> +**Ports mapping after deployment:**
```suggestion
**Port mappings required before deployment:**
```

2023-03-14 21:42 UTC, IanMadd requested changes
- All instances of "on-premise" should be replaced with "on-premises". That includes file names.
- Use underscores in filenames for consistency.
- There are three deployment methods, so there should be three deployment prerequisite pages.
- Change the menu titles to "Prerequisites"
- The value for the `gh_repo` property is just `automate`.
- You've got a few instances of "aws". AWS is an acronym so it's always capitalized unless you're talking about the CLI tool. 
- The menu parent and identifier should match the identifiers here: https://github.com/chef/chef-web-docs/pull/4053/files
- The menus for the three deployment pages should also be updated to use the same parent identifiers:
   - ha_onprim_deployment_procedure
   - ha_aws_deploy_steps
   - ha_aws_managed_deploy_steps

2023-03-16 12:59 UTC, kalroy commented
@dishanktiwari2501  Please create a story for all the feedbacks from @IanMadd . Merging it for the urgent release.

2023-03-16 12:59 UTC, merged