Dave/chef 707
chef/automate pull request #7798
Opened 2023-04-01 22:15 UTC by daveaugustus

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-04-05 02:43 UTC, kalroy requested changes
Coverage is pretty less. Add more UTs in the code to increase the coverage of the new code written

2023-04-05 02:43 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +func FileContainingAutomateHAInfraDetails() (string, error) {
Add tests for this function

2023-04-05 02:43 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +func getAutomateHAInfraDetails(filePath string) (*AutomateHAInfraDetails, error) {
Add test for this function

2023-04-05 02:43 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +	if len(strings.TrimSpace(automateHAInfraDetails.Outputs.SSHPort.Value)) > 0 {
This logic is not correct. We cannot return only if Port is available. The logic in the original function was to get user and port value from other string if those data are missing in the structure fields

2023-04-05 02:43 UTC, kalroy commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +func printInfo(automate *AutomateHAInfraDetails) error {
Add a test here

2023-04-05 09:53 UTC, daveaugustus commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +func FileContainingAutomateHAInfraDetails() (string, error) {
Done

2023-04-05 10:56 UTC, daveaugustus commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +func printInfo(automate *AutomateHAInfraDetails) error {
Done!

2023-04-11 11:47 UTC, daveaugustus commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +func getAutomateHAInfraDetails(filePath string) (*AutomateHAInfraDetails, error) {
@Dmaddu Because we need to make it tastable

2023-04-12 05:28 UTC, YashviJain01 commented on components/automate-cli/cmd/chef-automate/sshAutomateHA.go
> +func getAutomateHAInfraDetails(filePath string) (*AutomateHAInfraDetails, error) {
I changed this to previous function and added a new helper function.

2023-04-12 11:31 UTC, kalroy approved these changes

2023-04-12 13:30 UTC, Dmaddu requested changes

2023-04-12 13:30 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/info-ha.go
> +func printInfoTest(automate *AutomateHAInfraDetails, writer *bytes.Buffer) error {
Why the test method is added here?

2023-04-12 13:30 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/info-ha_test.go
> +	t.Run("Passed ", func(t *testing.T) {
please write the valid test

2023-04-13 14:48 UTC, daveaugustus commented
![Screenshot 2023-04-13 at 8 16 31 PM](https://user-images.githubusercontent.com/36985548/231797508-daa5a503-80ac-4487-9285-57c7b512ab87.png)

@kalroy  @Dmaddu and @YashviJain01  this is how it looks now as it was looking before...

2023-04-13 18:01 UTC, Dmaddu approved these changes

2023-04-13 18:01 UTC, merged