Upgrade with FileSystem Backup Locally
chef/automate pull request #7810
Opened 2023-04-10 08:43 UTC by SanjuPal01

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-04-12 10:06 UTC, kalroy approved these changes

2023-04-12 10:24 UTC, Dmaddu requested changes

2023-04-12 10:24 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
>  ## Upgrade with FileSystem Backup Locally
update to `Migration`

2023-04-12 10:24 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +- The Minimum version of Automate to perform migration is 4.x.
please mark the min version as 2020xxxxxxxx

2023-04-12 10:24 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +Follow the below steps for Automate HA when you are upgrading with On-Premises and AWS deployment (but not for AWS managed services).
This statement is not meaningful

2023-04-12 10:24 UTC, Dmaddu commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Transfer the `tar` bundle to one of the Chef Automate HA Frontend Nodes using the following command:
We have to transfer the file to Automate node, not the fronted node. Infact we have to do the restoration in Bastion node.

2023-04-12 11:53 UTC, dishanktiwari2501 approved these changes
Reviewed and Updated the Doc

2023-04-12 17:39 UTC, Dmaddu approved these changes

2023-04-13 03:45 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. If you haven't specified the location in the `config.toml` file, go to the `/var/opt/chef-automate/backups` location and create **Bundle** using the following command:
```suggestion
1. Go to the backup location mentioned in Automate config, but if you haven't specified the location go to the `/var/opt/chef-automate/backups` location and create **Bundle** using the following command:
```

2023-04-13 03:46 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Transfer the `tar` bundle to one of the Chef-Automate nodes of Automate HA using the following command:
```suggestion
1. Transfer the `tar` bundle to one of the Chef Automate nodes of Automate HA using the following command:
```

2023-04-13 03:47 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +        scp -i /path/to/key /path/to/backup-file user@host:/home/user
```suggestion
        scp -i </path/to/key> </path/to/backup-file> <user>@<host>:/home/<user>
```

2023-04-13 03:48 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +        scp -i /path/to/key /path/to/bootstrap.abb user@host:/home/user
```suggestion
        scp -i </path/to/key> </path/to/bootstrap.abb> <user>@<host>:/home/<user>
```

2023-04-13 03:49 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Go to the Chef-Automate node of Automate HA cluster, where we copied the `tar` file. Unzip the bundle using the following:
```suggestion
1. Go to the Chef Automate node of Automate HA cluster, where we copied the `tar` file. Unzip the bundle using the following:
```

2023-04-13 03:49 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Run the following command at the Chef-Automate node of Automate HA cluster to get the applied `config`:
```suggestion
1. Run the following command at the Chef Automate node of Automate HA cluster to get the applied `config`:
```

2023-04-13 03:51 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +        scp -i /path/to/key /path/to/bootstrap.abb user@host:/home/user
```suggestion
        scp -i </path/to/key> </path/to/bootstrap.abb> <user>@<host>:/home/<user>
```

2023-04-13 03:59 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Run the following command at the Chef-Automate node of Automate HA cluster to get the applied config:
```suggestion
1. Run the following command on the Chef Automate node of Automate HA cluster to get the applied config:
```

2023-04-13 04:02 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Stop all the frontend instances except where you saved the `current_config.toml` file at automate nodes in Automate HA Cluster. Run the following command to all the Automate and Chef Infra Server
```suggestion
1. Stop all the frontend instances except where you saved the `current_config.toml` file on Chef Automate nodes in Automate HA Cluster. Run the following command to all the Automate and Chef Infra Server nodes:
```

2023-04-13 04:05 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +    1. Run the below command to create the backup in the `/var/opt/chef-automate/backups` location unless you specify the location in the `config.toml` file.
```suggestion
    1. Run the below command to create the backup in the `/var/opt/chef-automate/backups` location unless you specify the location in the Standalone Automate config.
```

2023-04-13 04:07 UTC, vivek-yadav commented on components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
> +1. Stop all the frontend instances except where you saved the `current_config.toml` file at automate node in Automate HA Cluster. Run the following command to all the Automate and Chef Infra Server n
```suggestion
1. Stop all the frontend instances except where you saved the `current_config.toml` file on Chef Automate node in Automate HA Cluster. Run the following command to all the Automate and Chef Infra Server nodes:
```

2023-04-13 08:23 UTC, merged