Port Reachable API
chef/automate pull request #7903
Opened 2023-05-22 09:32 UTC by SanjuPal01

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-05-23 10:27 UTC, Dmaddu requested changes
please fix the pipelines

2023-05-23 11:00 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/portreachableservice/portreachable.go
> +		return errors.New("certificate error")
What is the certificate error which comes here, can we have some valid error?

2023-05-23 11:01 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/portreachableservice/portreachable.go
> +	caCertPool := x509.NewCertPool()
Add debugger log here as well, trying to connect to https server?

2023-05-23 11:01 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/portreachableservice/portreachable.go
> +	pr.log.Debug("URL: ", net.JoinHostPort(host, port))
Debugger logs here as well.

2023-05-23 16:31 UTC, kalroy requested changes

2023-05-24 07:56 UTC, SanjuPal01 commented on components/automate-cli/pkg/verifyserver/server/api/v1/portreachable.go
> +	if reqBody.DestinationNodeServiceProtocol == constants.HTTPS && reqBody.RootCA == "" {
We are getting only DestinationIP in request body. Hence we can't do this check. Firewall API need to perform this check.

2023-05-24 07:59 UTC, vivekshankar1 commented on components/automate-cli/pkg/verifyserver/server/api/v1/portreachable.go
> +		c.Next(&fiber.Error{Code: http.StatusBadRequest, Message: "please give rootCA value"})
```suggestion
		c.Next(&fiber.Error{Code: http.StatusBadRequest, Message: "RootCA value is mandatory for protocol HTTPS"})
```

2023-05-24 08:55 UTC, vivekshankar1 commented on components/automate-cli/pkg/verifyserver/services/portreachableservice/portreachable.go
> +	pr.log.Debug("Trying to connect TCP server")
please add some information with debug logs as well like protocol, host, port etc

2023-05-24 09:32 UTC, SanjuPal01 commented on components/automate-cli/pkg/verifyserver/server/api/v1/portreachable.go
> +		reqBody.DestinationNodePort == 0 ||
I added one extra check for port range. now this check only handle if user didn't give any port number then default int value 0 will be passed and this block will be executed. 
but if user gave some invalid port number like negative number then i am handling that seperately in the next if block.

2023-05-24 14:50 UTC, Sahiba3108 approved these changes

2023-05-24 15:42 UTC, kalroy approved these changes

2023-05-24 17:14 UTC, Dmaddu approved these changes

2023-05-25 17:05 UTC, merged