Firewall API
chef/automate pull request #7941
Opened 2023-06-02 10:31 UTC by SanjuPal01

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-06-05 19:52 UTC, Dmaddu requested changes

2023-06-05 19:52 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice.go
> +	httpReq, err := http.NewRequest("POST", url, bytes.NewBuffer([]byte(httpReqBodyJSON)))
httpReqBodyJSON is of type byte array only, why do we need to convert again here?
we can simply write `bytes.NewBuffer(httpReqBodyJSON)`

2023-06-05 19:52 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice.go
> +	httpReq, err := http.NewRequest("POST", url, bytes.NewBuffer([]byte(httpReqBodyJSON)))
use `http.MethodPost`  instead of `POST`

2023-06-05 19:52 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice_test.go
> +	PortReachablePassMockServer := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
please assert the request on the mock servers

2023-06-06 05:51 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice.go
> +	httpReq.Header.Set("Content-Type", "application/json")
Use constants here

2023-06-06 05:51 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice.go
> +		return nil, errors.New("Failed to Marshal: " + err.Error())
This message should be clear. Failed to Marshal/Unmarshal the response from Port reachability API

2023-06-06 18:11 UTC, Dmaddu approved these changes

2023-06-07 04:23 UTC, YashviJain01 approved these changes

2023-06-07 09:21 UTC, Sahiba3108 approved these changes

2023-06-07 11:17 UTC, merged