CHEF-727 : Version Command on Bastion
chef/automate pull request #7970
Opened 2023-06-19 10:39 UTC by shanmugapriya-tr

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-06-20 05:25 UTC, YashviJain01 commented on components/automate-cli/cmd/chef-automate/constants.go
> +	PGGETVERSIONCURLCMD = "PGPASSWORD=%s  hab pkg exec core/postgresql13  psql -U %s -h localhost -p 10145 -d postgres --dbname postgres -tAc 'SELECT version()'"
Can we have a version constant, what if the version gets changed in future, then this command will not work.

2023-06-20 06:14 UTC, shanmugapriya-tr commented on components/automate-cli/cmd/chef-automate/debug.go
> +	getVersionCmd.Flags().StringVar(&versionCmdFlags.endpoint, "endpoint", "", "The endpoint the service is listening on")
The flags were being set to the wrong versionCmd object, as a result of which, endpoint and connection timeout flags were coming up in docs under chef-automate version command. Corrected this

2023-06-20 11:51 UTC, Dmaddu requested changes
once made the suggested changes, will review the complete PR again

2023-06-20 11:51 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +	"github.com/ttacon/chalk"
please use `github.com/fatih/color` to render the styled text. We are using this package in our repository. You can avoid importing the new package

2023-06-21 05:38 UTC, daveaugustus approved these changes
Tested this application on HA (AWS Deployment), the commands are working fine. The error I hi-lighted yesterday is fixed. 

APPROVING!

2023-06-21 09:22 UTC, Dmaddu requested changes

2023-06-21 09:22 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +		writer.Println(color.New(color.Bold).Add(color.Underline).Sprint("Automate"))
make `Automate` as a constant

2023-06-21 09:22 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +		writer.Println(color.New(color.Bold).Add(color.Underline).Sprint("Chef Server"))
make `Chef Server` as constant

2023-06-21 09:22 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +		writer.Println(color.New(color.Bold).Add(color.Underline).Sprint("Opensearch"))
make `OpenSearch` as constant

2023-06-21 09:22 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +		writer.Println(color.New(color.Bold).Add(color.Underline).Sprint("Postgresql"))
Make `Postgresql` as constant

2023-06-21 09:22 UTC, Dmaddu commented on components/automate-cli/cmd/chef-automate/version.go
> +						services = append(services, "Automate")
use the constant instead of `Automate`, similarly for Chef Server, OpenSearch, Postgresql as well

2023-06-21 11:56 UTC, Dmaddu approved these changes

2023-06-21 12:01 UTC, YashviJain01 approved these changes

2023-06-21 13:31 UTC, Dmaddu requested changes
https://buildkite.com/chef/chef-automate-main-verify-private/builds/29691 
Pipelines are failing because of these changes only. Please address them

2023-06-21 16:27 UTC, Dmaddu approved these changes

2023-06-21 16:28 UTC, merged