[Print reporting output]Create CLI Verify subcommand which validates given Config toml file before Deployment
chef/automate pull request #7980
Opened 2023-06-21 10:35 UTC by atultherajput

### :nut_and_bolt: Description: What code changed, and why?
Print the report output in STDOUT.

### :chains: Related Resources
https://chefio.atlassian.net/browse/CHEF-3589
https://chefio.atlassian.net/browse/CHEF-2053
https://github.com/chef/automate/pull/7961

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-06-22 17:53 UTC, Dmaddu requested changes
please fix the automate-cli unit test pipeline and upload the demo video

2023-06-22 18:54 UTC, atultherajput commented
> Details

Done

2023-06-22 18:54 UTC, atultherajput commented
> please fix the automate-cli unit test pipeline and upload the demo video

Done.

2023-06-23 06:25 UTC, atultherajput commented on components/automate-cli/cmd/chef-automate/verify.go
> +	tb["postgresqlStatusTable"] = getStatusTable("PostgresSQL")
Done

2023-06-23 06:26 UTC, atultherajput commented on lib/reporting/helperForVerification.go
> +func VerificationReports(reports []VerificationReport, reporting Reporting, nodeInfoMap map[string][]Info) {
Because this function is only used directly from outside.

2023-06-23 06:26 UTC, atultherajput commented on components/automate-cli/cmd/chef-automate/verify.go
> +	postgresSQLSummaryTableTitle := fmt.Sprintf("Summary: PostgresSQL <Nodes> - %d", numberOfPostgresSQLNodes)
Done

2023-06-23 06:28 UTC, vviveksharma approved these changes

2023-06-23 07:00 UTC, vivekshankar1 approved these changes

2023-06-23 07:05 UTC, bvtejaswi commented
I think in Successful column we can add success_checks/total_checks instead of just giving 75 successful.
e.g. 75/75, 6/75 in success column

2023-06-23 07:14 UTC, atultherajput commented on components/automate-cli/cmd/chef-automate/verify.go
> +		return fmt.Errorf("batch-check API failed on remote nodes:\n%v", batchCheckResults)
done

2023-06-23 07:21 UTC, punitmundra approved these changes

2023-06-23 07:21 UTC, merged