Removing the check for day_latest flag in case of date range
chef/automate pull request #8106
Opened 2023-08-04 05:28 UTC by YashviJain01

### :nut_and_bolt: Description: What code changed, and why?

Day_latest flag was causing issue in the trends api as a date range was passed. If we put data for the same nodes on daily basis the graph should reflect changes

### :chains: Related Resources

https://chefio.atlassian.net/browse/CHEF-1693

### :+1: Definition of Done

Now the graph is available

### :athletic_shoe: How to Build and Test the Change

```
rebuild components/compliance-service/
Add data for the same nodes on various days using below:-
./automate-load-test -url https://a2-dev.test/api/v0/events/data-collector -token FpHxmuaUE6KevG0ZRWbCp31GWo4= -numberOfElement=10 -concurrency=5 -data=compliance -status=success -i/-o output.json
```

### :white_check_mark: Checklist

**All PRs** must tick these:

- [X] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [X] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [X] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [X] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [X] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [X] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [X] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [X] Tests added/updated? (all new code needs new tests)
- [X] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-08-04 10:57 UTC, daveaugustus approved these changes

2023-08-10 04:54 UTC, Dmaddu requested changes

2023-08-10 04:54 UTC, Dmaddu commented on components/compliance-service/reporting/relaxting/reports.go
> +	return []string{"daily_latest"}, nil
please validate the unit tests. Tests are failing https://buildkite.com/chef-oss/chef-automate-main-verify/builds/30146#0189bf0a-efbc-4e6b-9956-8cf8a4ba6b2a

2023-08-10 17:23 UTC, Dmaddu approved these changes

2023-08-10 17:24 UTC, merged