added values for config parser
chef/automate pull request #8141
Opened 2023-08-21 13:59 UTC by SahithiMy

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-08-23 10:20 UTC, daveaugustus requested changes

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfig_test.go
> +						Location:       "gcs",
```suggestion
						Location:       "GCS",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfig.go
> +		if objectStorageConfig.Location == "gcs" {
```suggestion
		if objectStorageConfig.Location == "GCS" {
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify.go
> +	if objectStorage.Location == "s3" {
```suggestion
	if objectStorage.Location == "S3" {
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/testdata/HaOnPremGcs.toml
> +location = "gcs"
```suggestion
location = "GCS"
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/testdata/HaOnPremGcsFailed.toml
> +location = "gcs"
```suggestion
location = "GCS"
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/testdata/UnmarshalErrorForGcs.toml
> +location = "gcs"
```suggestion
location = "GCS"
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfig_test.go
> +						Location:       "gcs",
```suggestion
						Location:       "GCS",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfig_test.go
> +						Location:       "gcs",
```suggestion
						Location:       "GCS",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify.go
> +	if objectStorage.Location == "gcs" {
```suggestion
	if objectStorage.Location == "GCS" {
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
```suggestion
				Location:   "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:  "s3",
```suggestion
				Location:  "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
```suggestion
				Location:   "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
```suggestion
				Location:   "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
```suggestion
				Location:   "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
```suggestion
				Location:   "S3",
```

2023-08-23 10:20 UTC, daveaugustus commented on lib/config/hadeployconfigverify_test.go
> +				Location: "gcs",
```suggestion
				Location: "GCS",
```

2023-08-24 07:37 UTC, YashviJain01 commented on lib/config/hadeployconfig.go
> +		if objectStorageConfig.Location == "gcs" {
We should create a constant fot this

2023-08-24 07:37 UTC, YashviJain01 commented on lib/config/hadeployconfig.go
> +			c.ObjectStorage.Config.Location = "s3"
for s3 as well

2023-08-24 07:56 UTC, SahithiMy commented
Pipeline: https://buildkite.com/chef/chef-automate-main-verify-private/builds/31831

2023-08-24 16:29 UTC, Dmaddu requested changes
some of the mandatory checks on the pipelines were not passed. Please fix them.

2023-08-25 09:54 UTC, daveaugustus approved these changes

2023-08-25 10:11 UTC, Dmaddu approved these changes

2023-08-25 10:11 UTC, merged