Dave/chef 5612
chef/automate pull request #8142
Opened 2023-08-21 21:46 UTC by daveaugustus

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-08-24 07:05 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/models/batchcheck.go
> +	if objectStorageConfig.Location == AWS_S3 {
Are we handling the case where location is empty and set to s3?

2023-08-24 07:12 UTC, YashviJain01 commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
Have we added test case for any successful case for gcs?

2023-08-24 07:13 UTC, YashviJain01 commented on lib/config/hadeployconfigverify_test.go
> +				Location:   "s3",
This should support the blank value, where location is not set.

2023-08-25 10:50 UTC, Dmaddu requested changes

2023-08-25 10:50 UTC, Dmaddu commented on lib/config/hadeployconfigverify.go
> +	if objectStorage.Location == AWS_S3 {
These are already available from line number 185

2023-08-25 10:50 UTC, Dmaddu commented on lib/config/testdata/gcsservicefile.json
> +}
There are no changes in this file, please remove this file from PR

2023-08-25 10:50 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/models/batchcheck.go
> +	GCP_CLOUD_STORAGE = "gcp"
Are we using GCP or GCS, please decide on one. In the previous PR, the constant was GCS, and in this its GCP. As per standalone it should be GCS

2023-08-25 10:50 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/models/batchcheck.go
> +	} else if objectStorageConfig.Location == GCP_CLOUD_STORAGE {
Do we have any validation if the provided value is neither s3 nor gcs?

2023-08-28 06:07 UTC, Dmaddu requested changes

2023-08-28 06:07 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/models/batchcheck.go
> +		logrus.Errorf("For now we don't support location: %s", objectStorageConfig.Location)
plz change this message

2023-08-28 07:40 UTC, daveaugustus commented
Pipeline:

https://buildkite.com/chef-oss/chef-automate-main-verify/builds/30647
https://buildkite.com/chef/chef-automate-main-verify-private/builds/31928

2023-08-28 08:11 UTC, Dmaddu approved these changes

2023-08-28 08:12 UTC, merged