Dave/chef 5613
chef/automate pull request #8159
Opened 2023-08-25 12:40 UTC by daveaugustus

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-08-31 11:02 UTC, Dmaddu requested changes

2023-08-31 11:02 UTC, Dmaddu commented on components/automate-cli/pkg/verifyserver/utils/gcputils/gcp.go
> +type GCPUtils interface {
Please make the changes as discussed

2023-08-31 11:06 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/gcpcloudstorageservice/gcpconfigservice.go
> +	ctx := context.Background()
Should we get this context from the Call itself?

2023-08-31 11:12 UTC, YashviJain01 commented on cspell.json
> -        "opensearch",
Why is this file here? Do we need this?

2023-08-31 11:15 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/constants/gcpconfig.go
> +	GCP_BUCKET_NOT_FOUND                = "Cannot find the Bucket in GCP cloud storage"
Should we rename GCP Cloud Storage to GCS?

2023-08-31 11:17 UTC, YashviJain01 commented on components/automate-cli/pkg/verifyserver/services/gcpcloudstorageservice/gcpconfigservice.go
> +var filePrefix = "gcp_check_test_"
Can we move this to constants file?

2023-08-31 11:19 UTC, YashviJain01 commented
Can you check the pipelines as well?

2023-08-31 12:11 UTC, daveaugustus commented on components/automate-cli/pkg/verifyserver/utils/gcputils/gcp.go
> +	_, err := fmt.Fprintf(wc, "Heute ist ein schöner Tag.")
"Today is a beautiful day"

2023-09-02 11:09 UTC, daveaugustus commented
https://github.com/chef/automate/assets/36985548/686e8eed-dc61-4df6-a0ba-3df1aa58d497

@Dmaddu please find the testing video

2023-09-02 13:09 UTC, merged