Yashvi/chef 5804
chef/automate pull request #8161
Opened 2023-08-28 04:28 UTC by YashviJain01

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-08-28 12:15 UTC, Dmaddu requested changes

2023-08-28 12:15 UTC, Dmaddu commented on components/license-control-service/licenseaudit/licenseauditworkflow.go
> +func getInterval(frequency string) rrule.Frequency {
Are we not supporting hourly?

2023-08-28 12:37 UTC, YashviJain01 commented on components/license-control-service/licenseaudit/licenseauditworkflow.go
> +func getInterval(frequency string) rrule.Frequency {
We can add, let me do that

2023-08-28 12:44 UTC, YashviJain01 commented on components/license-control-service/licenseaudit/licenseauditworkflow.go
> +func getInterval(frequency string) rrule.Frequency {
Addded.

2023-08-29 05:21 UTC, Dmaddu approved these changes

2023-08-29 05:23 UTC, Dmaddu commented
Hi @YashviJain01, Since you are adding config parameters, it would be good if you could also provide the demo of patching those parameters. Please make to include these things in the demo next time onwards. Approving for now.

2023-08-29 05:23 UTC, merged