Remvoing config patch for old configs in upgrade and add/remove node
chef/automate pull request #8296
Opened 2023-11-20 08:30 UTC by ArvinthC3000

### :nut_and_bolt: Description: What code changed, and why?
When user upgrade the bundle to latest, some configuration belongs to Automate config which are updated are reverting back to initial values. In this PR, that is addressed

### :chains: Related Resources
Jira ticket: https://chefio.atlassian.net/browse/CHEF-8418

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2023-11-20 09:24 UTC, punitmundra requested changes
bump the package automate-backend-deploment

2023-11-20 09:40 UTC, punitmundra approved these changes

2023-11-21 05:23 UTC, punitmundra approved these changes

2023-11-21 05:37 UTC, bvtejaswi approved these changes

2023-11-29 10:26 UTC, merged