Capitalization, Product Names, and Wordings
chef/automate pull request #8366
Opened 2024-02-12 10:36 UTC by dishanktiwari2501

### :nut_and_bolt: Description: What code changed, and why?

### :chains: Related Resources

* https://chefio.atlassian.net/browse/CHEF-2997
* The PR https://github.com/chef/automate/pull/7948 will be deleted once this one is merged.

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2024-02-13 14:59 UTC, IanMadd requested changes

2024-02-13 14:59 UTC, IanMadd commented on components/docs-chef-io/content/automate/elasticsearch.md
> -title = "Elasticsearch"
Elasticsearch has a lowercase _s_

2024-02-15 09:41 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/elasticsearch.md
> -title = "Elasticsearch"
It has already been fixed.

2024-02-19 23:23 UTC, IanMadd commented on components/docs-chef-io/content/automate/elasticsearch.md
> +title = "ElasticSearch"
This is not a lowercase _s_

2024-04-05 19:32 UTC, IanMadd requested changes
Look through here again. You still have "ElasticSearch" in a bunch of places.

2024-05-03 14:31 UTC, IanMadd commented on components/docs-chef-io/content/automate/backup.md
> +To delete backups from a running instance of Chef Automate, first find the relevant backup ID with `chef-automate backup list` and then delete the backup using [`Chef Automate backup delete ID`]({{<
This is code and not regular text:

```suggestion
To delete backups from a running instance of Chef Automate, first find the relevant backup ID with `chef-automate backup list` and then delete the backup using [`chef-automate backup delete ID`]({{< relref "cli/#chef-automate-backup-delete" >}}).
```

2024-05-03 14:31 UTC, IanMadd approved these changes

2024-08-28 05:07 UTC, merged