Updating docs and hiding old flags for cert rotate command
chef/automate pull request #8444
Opened 2024-05-07 05:32 UTC by jayvikramsharma1

### :nut_and_bolt: Description: What code changed, and why?
We are supporting rotate cluster certificates flags in certificate rotation, so old flags to update individual service or individual Ips certificates will be deprecates and we are hiding those flags, and updating the docs for the same

we have added remove unreachable nodes flag in add and remove node commands, updating doc for the same,

upgrading PG version in doc

### :chains: Related Resources

https://chefio.atlassian.net/browse/CHEF-11744

### :+1: Definition of Done

Doc changes

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

2024-05-07 07:46 UTC, punitmundra requested changes
Please add the screenshot in the ticket with the existing flag and removed flag.

2024-05-07 08:56 UTC, shaik80 approved these changes

2024-05-07 08:56 UTC, shaik80 commented on components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
> +
why are adding new lone here

2024-05-08 06:19 UTC, punitmundra approved these changes

2024-05-08 06:53 UTC, dishanktiwari2501 approved these changes

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
> +You can remove unreachable nodes while adding nodes
Add a full stop to end the line.

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
> +- To remove unreachable nodes while adding new nodes, pass the flag `--remove-unreachable-node` or `-r` like example below
Replace it with: - To remove unreachable nodes while adding new nodes, pass the flag `--remove-unreachable-node` or `-r` like the example below:

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
> +- Removing unreachable nodes while adding nodes is not supported in AWS mode of deployment, you have to use [remove node commands page](/automate/ha_remove_single_node_from_cluster/)
Replace it with: - Removing unreachable nodes while adding nodes is not supported in AWS mode of deployment; you have to use [remove node commands page](/automate/ha_remove_single_node_from_cluster/)

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md
> +You can remove other unreachable nodes while removing a node
Add a full step

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md
> +- To remove unreachable nodes while removing a node, pass the flag `--remove-unreachable-node` or `-r` like example below
Replace it with: - To remove unreachable nodes while removing a node, pass the flag `--remove-unreachable-node` or `-r` like the example below

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md
> +You can remove other unreachable nodes while removing a node
add full stop

2024-05-08 06:53 UTC, dishanktiwari2501 commented on components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md
> +- To remove unreachable nodes while removing a node, pass the flag `--remove-unreachable-node` or `-r` like example below
- To remove unreachable nodes while removing a node, pass the flag `--remove-unreachable-node` or `-r` like the example below:

2024-05-08 11:54 UTC, AnkurMundhra approved these changes
I can see that we are removing cert-rotate section for each service and node. If this is desired, then I am good.

2024-05-09 06:04 UTC, merged